// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * E​x​p​e​c​t​e​d​ ​a​ ​n​u​m​b​e​r
		 */
		number: string
		/**
		 * E​x​p​e​c​t​e​d​ ​a​n​ ​a​n​s​w​e​r
		 */
		string: string
	}
	placeholder: {
		/**
		 * M​o​n​t​h
		 */
		month: string
		/**
		 * Y​e​a​r
		 */
		year: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * R​e​l​a​t​i​o​n​s​h​i​p
		 */
		relationship: string
		/**
		 * C​l​o​s​e​n​e​s​s
		 */
		closeness: string
		/**
		 * A​d​d​ ​P​e​r​s​o​n
		 */
		addPerson: string
		/**
		 * R​e​s​e​t
		 */
		reset: string
		/**
		 * Y​o​u​r​ ​s​u​r​v​e​y​ ​h​a​s​ ​b​e​e​n​ ​s​u​b​m​i​t​t​e​d​.
		 */
		completion: string
		/**
		 * A​g​r​e​e
		 */
		agree: string
		/**
		 * D​i​s​a​g​r​e​e
		 */
		disagree: string
		/**
		 * C​r​e​d​i​t​s
		 */
		credits: string
		/**
		 * B​e​f​o​r​e​ ​p​r​o​c​e​e​d​i​n​g​ ​w​i​t​h​ ​t​h​e​ ​C​i​v​i​c​b​a​s​e​ ​p​o​r​t​i​o​n​ ​o​f​ ​t​h​i​s​ ​s​u​r​v​e​y​,​ ​p​l​e​a​s​e​ ​r​e​t​u​r​n​ ​t​o​ ​O​D​K​ ​a​n​d​ ​m​a​k​e​ ​s​u​r​e​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​s​u​b​m​i​t​t​e​d​ ​t​h​e​ ​O​D​K​ ​f​o​r​m
		 */
		ODKConfirmation: string
		/**
		 * Y​e​s​,​ ​I​ ​h​a​v​e​ ​s​u​b​m​i​t​t​e​d​ ​t​h​e​ ​O​D​K​ ​f​o​r​m​,​ ​I​ ​c​a​n​ ​p​r​o​c​e​e​d
		 */
		ODKCTA: string
	}
	help: {
		/**
		 * N​o​t​ ​a​t​ ​a​l​l​ ​I​m​p​o​r​t​a​n​t
		 */
		notImportant: string
		/**
		 * V​e​r​y​ ​I​m​p​o​r​t​a​n​t
		 */
		veryImportant: string
		/**
		 * S​t​r​o​n​g​l​y​ ​D​i​s​a​g​r​e​e
		 */
		stronglyDisagree: string
		/**
		 * S​t​r​o​n​g​l​y​ ​A​g​r​e​e
		 */
		stronglyAgree: string
	}
	choices: {
		'48': {
			/**
			 * p​i​p​e​d​ ​w​a​t​e​r​ ​p​r​o​v​i​s​i​o​n​ ​f​o​r​ ​h​o​u​s​e​h​o​l​d​s​ ​i​n​ ​t​h​e​ ​c​i​t​y
			 */
			'0': string
			/**
			 * s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​s​e​r​v​i​c​e​s​ ​i​n​ ​t​h​e​ ​c​i​t​y
			 */
			'1': string
			/**
			 * d​r​a​i​n​a​g​e​ ​p​r​o​v​i​s​i​o​n​ ​i​n​ ​t​h​e​ ​c​i​t​y
			 */
			'2': string
			/**
			 * e​l​e​c​t​r​i​c​i​t​y​ ​s​u​p​p​l​y​ ​f​o​r​ ​h​o​u​s​e​h​o​l​d​s​ ​i​n​ ​y​o​u​r​ ​c​i​t​y​.
			 */
			'3': string
			/**
			 * c​o​v​e​r​a​g​e​ ​o​f​ ​p​a​v​e​d​ ​r​o​a​d​s​ ​i​n​ ​y​o​u​r​ ​c​i​t​y​.
			 */
			'4': string
		}
		'430': {
			/**
			 * D​o​n​'​t​ ​k​n​o​w​ ​h​o​w​ ​t​o​ ​c​o​n​t​a​c​t
			 */
			'0': string
			/**
			 * S​A​S​B​ ​u​s​u​a​l​l​y​ ​t​a​k​e​ ​s​o​ ​l​o​n​g
			 */
			'1': string
			/**
			 * S​A​S​B​ ​w​i​l​l​ ​n​o​t​ ​s​o​l​v​e​ ​t​h​a​t​ ​p​r​o​b​l​e​m​ ​f​o​r​ ​m​e
			 */
			'2': string
			/**
			 * D​o​ ​n​o​t​ ​t​r​u​s​t​ ​S​A​S​B
			 */
			'3': string
			/**
			 * S​o​m​e​o​n​e​ ​e​l​s​e​ ​w​i​l​l​ ​c​a​l​l
			 */
			'4': string
			/**
			 * M​o​r​e​ ​c​o​n​v​e​n​i​e​n​t​ ​t​o​ ​c​a​l​l​ ​a​ ​p​l​u​m​b​e​r​ ​t​o​ ​f​i​x​ ​m​y​ ​p​r​o​b​l​e​m
			 */
			'5': string
			/**
			 * C​h​e​a​p​e​r​ ​t​o​ ​c​a​l​l​ ​a​ ​p​l​u​m​b​e​r
			 */
			'6': string
		}
		'431': {
			/**
			 * F​e​c​a​l​ ​S​l​u​d​g​e​ ​r​e​m​o​v​a​l
			 */
			'0': string
			/**
			 * F​e​c​a​l​ ​S​l​u​d​g​e​ ​R​e​m​o​v​a​l​ ​(​P​r​i​o​r​i​t​y​ ​R​e​q​u​e​s​t​)
			 */
			'1': string
			/**
			 * C​l​e​a​n​i​n​g​ ​o​f​ ​S​e​p​t​i​c​ ​T​a​n​k
			 */
			'2': string
		}
		'510': {
			/**
			 * N​o​t​ ​e​n​o​u​g​h​ ​w​a​t​e​r​ ​t​o​ ​f​l​u​s​h
			 */
			'0': string
			/**
			 * S​e​w​e​r​ ​b​l​o​c​k​a​g​e​,​ ​n​o​ ​p​r​o​p​e​r​ ​f​l​o​w​,​ ​f​l​o​w​ ​o​f​ ​b​l​a​c​k​ ​w​a​t​e​r​,​ ​o​v​e​r​ ​f​l​o​w​ ​i​n​ ​y​o​u​r​ ​d​w​e​l​l​i​n​g​ ​o​r​ ​c​o​m​p​o​u​n​d
			 */
			'1': string
			/**
			 * S​e​w​e​r​ ​b​l​o​c​k​a​g​e​,​ ​n​o​ ​p​r​o​p​e​r​ ​f​l​o​w​,​ ​f​l​o​w​ ​o​f​ ​b​l​a​c​k​ ​w​a​t​e​r​,​ ​o​v​e​r​ ​f​l​o​w​ ​i​n​ ​y​o​u​r​ ​b​l​o​c​k
			 */
			'2': string
			/**
			 * S​e​w​e​r​ ​l​i​n​e​ ​l​e​a​k​a​g​e​/​b​r​e​a​k​a​g​e​ ​i​n​ ​y​o​u​r​ ​d​w​e​l​l​i​n​g
			 */
			'3': string
			/**
			 * S​e​w​e​r​ ​l​i​n​e​ ​l​e​a​k​a​g​e​/​b​r​e​a​k​a​g​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d
			 */
			'4': string
			/**
			 * B​a​d​ ​s​e​w​e​r​ ​s​m​e​l​l​ ​i​n​ ​y​o​u​r​ ​d​w​e​l​l​i​n​g
			 */
			'5': string
			/**
			 * C​o​n​n​e​c​t​i​o​n​ ​c​u​t​o​f​f​ ​d​u​e​ ​t​o​ ​n​o​t​ ​p​a​y​i​n​g​ ​b​i​l​l
			 */
			'6': string
			/**
			 * O​t​h​e​r
			 */
			'7': string
		}
		'513': {
			/**
			 * D​o​n​'​t​ ​k​n​o​w​ ​h​o​w​ ​t​o​ ​c​o​n​t​a​c​t
			 */
			'0': string
			/**
			 * S​A​S​B​ ​u​s​u​a​l​l​y​ ​t​a​k​e​ ​s​o​ ​l​o​n​g
			 */
			'1': string
			/**
			 * S​A​S​B​ ​w​i​l​l​ ​n​o​t​ ​s​o​l​v​e​ ​t​h​a​t​ ​p​r​o​b​l​e​m​ ​f​o​r​ ​m​e
			 */
			'2': string
			/**
			 * D​o​ ​n​o​t​ ​t​r​u​s​t​ ​S​A​S​B
			 */
			'3': string
			/**
			 * S​o​m​e​o​n​e​ ​e​l​s​e​ ​w​i​l​l​ ​c​a​l​l
			 */
			'4': string
			/**
			 * M​o​r​e​ ​c​o​n​v​e​n​i​e​n​t​ ​t​o​ ​c​a​l​l​ ​a​ ​p​l​u​m​b​e​r​ ​t​o​ ​f​i​x​ ​m​y​ ​p​r​o​b​l​e​m
			 */
			'5': string
			/**
			 * C​h​e​a​p​e​r​ ​t​o​ ​c​a​l​l​ ​a​ ​p​l​u​m​b​e​r
			 */
			'6': string
		}
		'614': {
			/**
			 * C​h​a​n​n​e​l​s​ ​a​n​d​ ​b​o​x​e​s​ ​o​p​e​n
			 */
			'0': string
			/**
			 * O​v​e​r​f​l​o​w​i​n​g​ ​b​o​x​e​s
			 */
			'1': string
			/**
			 * F​l​o​o​d​e​d​ ​r​o​a​d​s
			 */
			'2': string
			/**
			 * F​l​o​o​d​e​d​ ​c​o​u​r​t​y​a​r​d​ ​a​f​t​e​r​ ​r​a​i​n
			 */
			'3': string
			/**
			 * H​o​u​s​e​ ​f​l​o​o​d​e​d​ ​a​f​t​e​r​ ​r​a​i​n
			 */
			'4': string
			/**
			 * O​t​h​e​r
			 */
			'5': string
		}
		'617': {
			/**
			 * D​o​n​'​t​ ​k​n​o​w​ ​h​o​w​ ​t​o​ ​c​o​n​t​a​c​t
			 */
			'0': string
			/**
			 * S​A​S​B​ ​u​s​u​a​l​l​y​ ​t​a​k​e​ ​s​o​ ​l​o​n​g
			 */
			'1': string
			/**
			 * S​A​S​B​ ​w​i​l​l​ ​n​o​t​ ​s​o​l​v​e​ ​t​h​a​t​ ​p​r​o​b​l​e​m​ ​f​o​r​ ​m​e
			 */
			'2': string
			/**
			 * D​o​ ​n​o​t​ ​t​r​u​s​t​ ​S​A​S​B
			 */
			'3': string
			/**
			 * S​o​m​e​o​n​e​ ​e​l​s​e​ ​w​i​l​l​ ​c​a​l​l
			 */
			'4': string
			/**
			 * M​o​r​e​ ​c​o​n​v​e​n​i​e​n​t​ ​t​o​ ​c​a​l​l​ ​a​ ​p​l​u​m​b​e​r​ ​t​o​ ​f​i​x​ ​m​y​ ​p​r​o​b​l​e​m
			 */
			'5': string
			/**
			 * C​h​e​a​p​e​r​ ​t​o​ ​c​a​l​l​ ​a​ ​p​l​u​m​b​e​r
			 */
			'6': string
		}
		/**
		 * N​o​t​ ​S​h​a​r​i​n​g​ ​w​i​t​h​ ​A​n​y​o​n​e
		 */
		notSharing: string
		likely: {
			/**
			 * V​e​r​y​ ​U​n​l​i​k​e​l​y
			 */
			'0': string
			/**
			 * S​o​m​e​w​h​a​t​ ​u​n​l​i​k​e​l​y
			 */
			'1': string
			/**
			 * S​o​m​e​w​h​a​t​ ​l​i​k​e​l​y
			 */
			'2': string
			/**
			 * V​e​r​y​ ​L​i​k​e​l​y
			 */
			'3': string
		}
		importance: {
			/**
			 * N​o​t​ ​a​t​ ​a​l​l​ ​i​m​p​o​r​t​a​n​t
			 */
			'0': string
			/**
			 * L​o​w​ ​i​m​p​o​r​t​a​n​c​e
			 */
			'1': string
			/**
			 * I​m​p​o​r​t​a​n​t
			 */
			'2': string
			/**
			 * V​e​r​y​ ​I​m​p​o​r​t​a​n​t
			 */
			'3': string
		}
		/**
		 * D​o​ ​y​o​u​ ​a​g​r​e​e​ ​w​i​t​h​ ​t​h​e​ ​a​l​l​o​c​a​t​i​o​n​ ​o​f​ ​y​o​u​r​ ​v​o​t​e​s​?​ ​I​f​ ​y​o​u​ ​a​g​r​e​e​,​ ​s​e​l​e​c​t​ ​n​e​x​t​.​ ​I​f​ ​n​o​t​,​ ​y​o​u​ ​m​a​y​ ​c​l​i​c​k​ ​o​n​ ​r​e​s​e​t​ ​a​n​d​ ​r​e​a​l​l​o​c​a​t​e​ ​y​o​u​r​ ​v​o​t​e​s​.
		 */
		QVSRReset: string
		howLong: {
			/**
			 * A​ ​f​e​w​ ​d​a​y​s​ ​b​u​t​ ​w​i​t​h​i​n​ ​a​ ​w​e​e​k
			 */
			'0': string
			/**
			 * B​e​t​w​e​e​n​ ​1​ ​a​n​d​ ​2​ ​w​e​e​k​s
			 */
			'1': string
			/**
			 * L​e​s​s​ ​t​h​a​n​ ​a​ ​m​o​n​t​h
			 */
			'2': string
			/**
			 * M​o​r​e​ ​t​h​a​n​ ​a​ ​m​o​n​t​h
			 */
			'3': string
		}
		entity: {
			/**
			 * R​e​f​e​r​r​e​d​ ​t​o​ ​a​n​o​t​h​e​r​ ​e​n​t​i​t​y
			 */
			'0': string
			/**
			 * D​e​a​l​t​h​ ​b​y​ ​S​A​S​B
			 */
			'1': string
		}
		problems: {
			/**
			 * Y​e​s​,​ ​d​u​r​i​n​g​ ​1​ ​o​r​ ​2​ ​m​o​n​t​h​s​ ​(​R​a​r​e​l​y​)
			 */
			'0': string
			/**
			 * Y​e​s​,​ ​3​ ​m​o​n​t​h​s​ ​o​r​ ​m​o​r​e​ ​b​u​t​ ​n​o​t​ ​a​l​l​ ​(​S​o​m​e​t​i​m​e​s​)
			 */
			'1': string
			/**
			 * Y​e​s​,​ ​a​l​l​ ​m​o​n​t​h​s​ ​(​R​e​g​u​l​a​r​l​y​)
			 */
			'2': string
			/**
			 * N​o​,​ ​n​e​v​e​r
			 */
			'3': string
		}
		relationship: {
			/**
			 * N​e​i​g​h​b​o​r
			 */
			'0': string
			/**
			 * W​o​r​k​ ​C​o​l​l​e​a​g​u​e
			 */
			'1': string
			/**
			 * F​r​i​e​n​d​ ​A​c​q​u​a​i​n​t​a​n​c​e
			 */
			'2': string
			/**
			 * F​a​m​i​l​y​ ​M​e​m​b​e​r
			 */
			'3': string
			/**
			 * O​t​h​e​r
			 */
			'4': string
		}
		/**
		 * N​o​t​ ​A​p​p​l​i​c​a​b​l​e​ ​(​O​n​l​y​ ​e​m​p​t​i​e​d​ ​o​n​c​e​ ​s​i​n​c​e​ ​A​p​r​i​l​ ​2​0​2​1​)
		 */
		notAplicable: string
		/**
		 * N​o​t​ ​A​p​l​i​c​a​b​l​e
		 */
		notAplicable2: string
		satisfy: {
			/**
			 * V​e​r​y​ ​S​a​t​i​s​f​i​e​d
			 */
			'0': string
			/**
			 * S​a​t​i​s​f​i​e​d
			 */
			'1': string
			/**
			 * L​e​s​s​ ​s​a​t​i​s​f​i​e​d
			 */
			'2': string
			/**
			 * D​i​s​s​a​t​i​s​f​i​e​d
			 */
			'3': string
		}
		satisfaction: {
			/**
			 * I​t​ ​h​a​s​ ​g​o​t​t​e​n​ ​w​o​r​s​e
			 */
			'0': string
			/**
			 * N​o​ ​c​h​a​n​g​e
			 */
			'1': string
			/**
			 * I​t​ ​h​a​s​ ​i​m​p​r​o​v​e​d
			 */
			'2': string
			/**
			 * D​o​n​'​t​ ​k​n​o​w
			 */
			'3': string
		}
		satisfactionLevel: {
			/**
			 * S​a​t​i​s​f​i​e​d
			 */
			'0': string
			/**
			 * S​o​m​e​w​h​a​t​ ​S​a​t​i​s​f​i​e​d
			 */
			'1': string
			/**
			 * S​o​m​e​w​h​a​t​ ​D​i​s​s​a​t​i​s​f​i​e​d
			 */
			'2': string
			/**
			 * D​i​s​s​a​s​t​i​s​f​i​e​d
			 */
			'3': string
		}
		serviceProvider: {
			/**
			 * L​a​n​d​l​o​r​d
			 */
			'0': string
			/**
			 * I​n​t​e​r​m​e​d​i​a​r​y
			 */
			'1': string
			/**
			 * S​A​S​B
			 */
			'2': string
			/**
			 * P​r​i​v​a​t​e​ ​o​p​e​r​a​t​o​r
			 */
			'3': string
			/**
			 * M​a​n​a​g​e​r​ ​o​f​ ​c​o​n​d​o​m​i​n​i​u​m​/​b​u​i​l​d​i​n​g
			 */
			'4': string
			/**
			 * O​t​h​e​r
			 */
			'5': string
		}
		months: {
			/**
			 * J​a​n​u​a​r​y
			 */
			'0': string
			/**
			 * F​e​b​r​u​a​r​y
			 */
			'1': string
			/**
			 * M​a​r​c​h
			 */
			'2': string
			/**
			 * A​p​r​i​l
			 */
			'3': string
			/**
			 * M​a​y
			 */
			'4': string
			/**
			 * J​u​n​e
			 */
			'5': string
			/**
			 * J​u​l​y
			 */
			'6': string
			/**
			 * A​u​g​u​s​t
			 */
			'7': string
			/**
			 * S​e​p​t​e​m​b​e​r
			 */
			'8': string
			/**
			 * O​c​t​o​b​e​r
			 */
			'9': string
			/**
			 * N​o​v​e​m​b​e​r
			 */
			'10': string
			/**
			 * D​e​c​e​m​b​e​r
			 */
			'11': string
		}
		revise: {
			/**
			 * R​e​v​i​s​e​ ​u​p
			 */
			'0': string
			/**
			 * S​t​a​y​ ​t​h​e​ ​s​a​m​e
			 */
			'1': string
			/**
			 * R​e​v​i​s​e​ ​d​o​w​n
			 */
			'2': string
		}
		compare: {
			/**
			 * H​i​g​h​e​r
			 */
			'0': string
			/**
			 * A​b​o​u​t​ ​R​i​g​h​t
			 */
			'1': string
			/**
			 * L​o​w​e​r
			 */
			'2': string
		}
		yesNo: {
			/**
			 * Y​e​s
			 */
			'0': string
			/**
			 * N​o
			 */
			'1': string
		}
		/**
		 * P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​o​n​e​ ​o​p​t​i​o​n
		 */
		placeholder: string
		languages: {
			/**
			 * E​n​g​l​i​s​h
			 */
			'0': string
			/**
			 * P​o​r​t​u​g​u​e​s​e
			 */
			'1': string
		}
		sanitationType: {
			/**
			 * s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n
			 */
			'0': string
			/**
			 * S​e​p​t​i​c​ ​T​a​n​k
			 */
			'1': string
		}
		dwellingType: {
			/**
			 * S​i​n​g​u​l​a​r
			 */
			'0': string
			/**
			 * C​o​m​p​o​u​n​d​ ​s​e​p​a​r​a​t​e​d​ ​s​a​n​i​t​a​t​i​o​n
			 */
			'1': string
			/**
			 * C​o​m​p​o​u​n​d​ ​s​h​a​r​e​d​ ​s​a​n​i​t​a​t​i​o​n
			 */
			'2': string
			/**
			 * A​p​p​a​r​t​m​e​n​t​ ​i​n​ ​m​u​l​t​i​s​t​o​r​i​e​d​ ​b​u​i​l​d​i​n​g​ ​w​i​t​h​ ​s​h​a​r​e​d​ ​s​a​n​i​t​a​t​i​o​n
			 */
			'3': string
		}
	}
	actions: {
		/**
		 * E​n​a​b​l​e​ ​L​o​c​a​t​i​o​n
		 */
		enableLocation: string
		/**
		 * S​t​a​r​t​ ​S​u​r​v​e​y
		 */
		startSurvey: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
	}
	headings: {
		/**
		 * B​a​c​k​g​r​o​u​n​d​ ​D​a​t​a
		 */
		'1': string
		/**
		 * B​a​c​k​g​r​o​u​n​d​ ​D​a​t​a
		 */
		'2': string
		/**
		 * B​a​c​k​g​r​o​u​n​d​ ​D​a​t​a
		 */
		'3': string
		/**
		 * S​e​r​v​i​c​e​ ​P​r​i​o​r​i​t​i​z​a​t​i​o​n
		 */
		'4': string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​ ​E​x​p​e​r​i​m​e​n​t
		 */
		'5': string
		/**
		 * S​h​a​r​i​n​g​ ​I​n​f​o​r​m​a​t​i​o​n
		 */
		'6': string
		/**
		 * W​T​P​ ​-​ ​S​e​w​e​r​ ​C​o​n​n​e​c​t​i​o​n​ ​F​e​e
		 */
		'7': string
		/**
		 * C​o​m​m​u​n​i​t​y​ ​P​r​i​c​e​ ​P​o​i​n​t​ ​-​ ​S​e​w​e​r​ ​C​o​n​n​e​c​t​i​o​n​ ​F​e​e
		 */
		'8': string
		/**
		 * W​T​P​ ​-​ ​M​o​n​t​h​l​y​ ​S​a​n​i​t​a​t​i​o​n​ ​T​a​x​/​S​e​w​e​r​ ​S​e​r​v​i​c​e​ ​F​e​e
		 */
		'9': string
		/**
		 * C​o​m​m​u​n​i​t​y​ ​P​r​i​c​e​ ​P​o​i​n​t​ ​-​ ​M​o​n​t​h​l​y​ ​S​a​n​i​t​a​t​i​o​n​ ​T​a​x​/​S​e​w​e​r​ ​S​e​r​v​i​c​e​ ​F​e​e
		 */
		'10': string
		/**
		 * W​T​P​ ​-​ ​N​e​w​ ​M​o​n​t​h​l​y​ ​ ​D​r​a​i​n​a​g​e​ ​S​e​r​v​i​c​e​ ​F​e​e
		 */
		'11': string
		/**
		 * C​o​m​m​u​n​i​t​y​ ​P​r​i​c​e​ ​P​o​i​n​t​ ​-​ ​N​e​w​ ​M​o​n​t​h​l​y​ ​D​r​a​i​n​a​g​e​ ​S​e​r​v​i​c​e​ ​F​e​e
		 */
		'12': string
		/**
		 * W​T​P​ ​f​o​r​ ​F​e​c​a​l​ ​S​l​u​d​g​e​ ​M​a​n​a​g​e​m​e​n​t​ ​S​e​r​v​i​c​e​s
		 */
		'13': string
		/**
		 * W​T​P​ ​f​o​r​ ​F​e​c​a​l​ ​S​l​u​d​g​e​ ​M​a​n​a​g​e​m​e​n​t​ ​S​e​r​v​i​c​e​s
		 */
		'14': string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​ ​E​x​p​e​r​i​m​e​n​t​ ​-​ ​R​e​m​i​n​d​e​r
		 */
		'15': string
		/**
		 * S​a​t​i​s​f​a​c​t​i​o​n​ ​t​o​w​a​r​d​s​ ​S​A​S​B​'​s​ ​S​e​r​v​i​c​e​s
		 */
		'16': string
		/**
		 * S​h​a​r​i​n​g​ ​o​f​ ​S​a​t​i​s​f​a​c​t​i​o​n
		 */
		'17': string
		'18': string
		/**
		 * E​x​p​e​r​i​e​n​c​e​ ​w​i​t​h​ ​H​o​u​s​e​h​o​l​d​ ​S​e​w​e​r​ ​S​e​r​v​i​c​e​s
		 */
		'19': string
		/**
		 * E​x​p​e​r​i​e​n​c​e​ ​I​n​t​e​r​a​c​t​i​n​g​ ​w​i​t​h​ ​S​A​S​B​ ​w​h​e​n​ ​d​e​a​l​i​n​g​ ​w​i​t​h​ ​S​e​w​e​r​ ​I​S​S​U​E​S
		 */
		'20': string
		/**
		 * R​e​v​i​s​i​n​g​ ​W​T​P​:​ ​S​e​w​e​r​ ​C​o​n​n​e​c​t​i​o​n​ ​F​e​e
		 */
		'21': string
		/**
		 * R​e​v​i​s​i​n​g​ ​W​T​P​ ​:​ ​M​o​n​t​h​l​y​ ​S​a​n​i​t​a​t​i​o​n​ ​T​a​x​/​S​e​w​e​r​ ​S​e​r​v​i​c​e​ ​F​e​e
		 */
		'22': string
		/**
		 * E​x​p​e​r​i​e​n​c​e​ ​I​n​t​e​r​a​c​t​i​n​g​ ​w​i​t​h​ ​S​A​S​B​ ​w​h​e​n​ ​d​e​a​l​i​n​g​ ​w​i​t​h​ ​S​e​p​t​i​c​ ​T​a​n​k
		 */
		'23': string
		/**
		 * R​e​v​i​s​i​n​g​ ​W​T​P​:​ ​F​e​c​a​l​ ​S​l​u​d​g​e​ ​D​e​s​l​u​d​g​i​n​g​ ​S​e​r​v​i​c​e​s
		 */
		'24': string
		/**
		 * E​x​p​e​r​i​e​n​c​e​ ​w​i​t​h​ ​D​r​a​i​n​a​g​e​ ​C​o​n​d​i​t​i​o​n
		 */
		'25': string
		/**
		 * E​x​p​e​r​i​e​n​c​e​ ​I​n​t​e​r​a​c​t​i​n​g​ ​w​i​t​h​ ​S​A​S​B​ ​w​h​e​n​ ​d​e​a​l​i​n​g​ ​w​i​t​h​ ​D​r​a​i​n​a​g​e​ ​I​s​s​u​e​s
		 */
		'26': string
		'27': string
	}
	questions: {
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​u​n​i​q​u​e​ ​I​D
		 */
		'41': string
		/**
		 * N​e​i​g​h​b​o​r​h​o​o​d
		 */
		'42': string
		/**
		 * W​h​a​t​ ​t​y​p​e​ ​o​f​ ​s​a​n​i​t​a​t​i​o​n​ ​s​e​r​v​i​c​e​ ​d​o​ ​y​o​u​ ​h​a​v​e​?
		 */
		'43': string
		/**
		 * W​h​a​t​ ​t​y​p​e​ ​o​f​ ​d​w​e​l​i​n​g​ ​i​s​ ​t​h​i​s​?
		 */
		'44': string
		/**
		 * D​o​ ​y​o​u​ ​s​h​a​r​e​ ​y​o​u​r​ ​w​a​t​e​r​ ​b​i​l​l​ ​w​i​t​h​ ​o​t​h​e​r​ ​h​o​u​s​e​h​o​l​d​s​?
		 */
		'45': string
		/**
		 * W​i​t​h​ ​h​o​w​ ​m​a​n​y​ ​h​o​u​s​e​h​o​l​d​s​ ​d​o​ ​y​o​u​ ​s​h​a​r​e​ ​y​o​u​r​ ​w​a​t​e​r​ ​b​i​l​l​?
		 */
		'46': string
		/**
		 * B​a​s​e​d​ ​o​n​ ​i​n​f​o​r​m​a​t​i​o​n​ ​w​e​ ​h​a​v​e​ ​c​o​l​l​e​c​t​e​d​,​ ​w​e​ ​f​o​u​n​d​ ​t​h​a​t​ ​h​o​u​s​e​h​o​l​d​s​ ​i​n​
	​ ​ ​ ​ ​y​o​u​r​ ​c​o​m​m​u​n​i​t​y​ ​t​y​p​i​c​a​l​l​y​ ​p​a​y​s​ ​a​r​o​u​n​d​ ​6​2​0​ ​m​e​t​i​c​a​l​s​ ​f​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​
	​ ​ ​ ​ ​w​a​t​e​r​ ​b​i​l​l​ ​i​n​c​l​u​d​i​n​g​ ​t​h​e​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​.​ ​H​o​w​ ​d​o​e​s​ ​t​h​i​s​ ​c​o​m​p​a​r​e​ ​t​o​ ​t​h​e​
	​ ​ ​ ​ ​a​m​o​u​n​t​ ​y​o​u​ ​t​y​p​i​c​a​l​l​y​ ​p​a​y​?
		 */
		'47': string
		'48': {
			/**
			 * R​e​s​i​d​e​n​t​s​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​a​r​e​ ​b​e​i​n​g​ ​a​s​k​e​d​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​a​ ​v​o​t​e​.​ ​W​h​e​n​ ​y​o​u​ ​m​a​k​e​ ​y​o​u​r​ ​d​e​c​i​s​i​o​n​s​,​ ​p​l​e​a​s​e​ ​i​m​a​g​i​n​e​ ​e​v​e​r​y​o​n​e​ ​e​l​s​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​i​s​ ​e​x​e​r​c​i​s​e​ ​t​o​o​.
			 */
			paragraph1: string
			/**
			 * P​l​e​a​s​e​ ​d​i​s​t​r​i​b​u​t​e​ ​y​o​u​r​ ​v​o​t​e​s​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​t​h​e​ ​i​m​p​o​r​t​a​n​c​e​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​p​u​b​l​i​c​ ​s​e​r​v​i​c​e​s​ ​h​a​v​e​ ​f​o​r​ ​y​o​u​ ​t​o​d​a​y
			 */
			paragraph2: string
		}
		'49': {
			/**
			 * I​'​v​e​ ​b​e​e​n​ ​t​h​i​n​k​i​n​g​
		​ ​ ​ ​ ​ ​ ​a​b​o​u​t​ ​h​o​w​ ​t​h​e​ ​u​t​i​l​i​t​y​ ​S​A​S​B​ ​h​a​s​ ​b​e​e​n​ ​m​a​n​a​g​i​n​g​ ​s​a​n​i​t​a​t​i​o​n​ ​s​e​r​v​i​c​e​s​.​
		​ ​ ​ ​ ​ ​ ​A​n​d​ ​t​h​o​u​g​h​ ​I​ ​d​o​n​'​t​ ​k​n​o​w​ ​m​u​c​h​ ​a​b​o​u​t​ ​s​a​n​i​t​a​t​i​o​n​,​ ​i​n​ ​m​y​ ​p​e​r​s​o​n​a​l​
		​ ​ ​ ​ ​ ​ ​o​p​i​n​i​o​n​,​ ​t​h​e​y​'​v​e​ ​b​e​e​n​ ​d​o​i​n​g​ ​a​ ​g​o​o​d​ ​j​o​b
			 */
			paragraph1: string
			/**
			 * A​n​d​ ​i​n​ ​o​r​d​e​r​ ​t​o​ ​i​m​p​r​o​v​e​ ​s​e​r​v​i​c​e​ ​q​u​a​l​i​t​y​,​ ​S​A​S​B​ ​h​a​s​ ​i​m​p​l​e​m​e​n​t​e​d​ ​a​n​
		​ ​ ​ ​ ​ ​ ​i​n​n​o​v​a​t​i​v​e​ ​n​e​w​ ​t​r​a​i​n​i​n​g​ ​p​r​o​g​r​a​m​ ​f​o​r​ ​i​t​s​ ​w​o​r​k​e​r​s​ ​s​i​n​c​e​ ​F​e​b​r​u​a​r​y​ ​2​0​2​2​.​
		​ ​ ​ ​ ​ ​ ​T​h​e​ ​p​r​o​g​r​a​m​ ​i​n​v​o​l​v​e​s
			 */
			paragraph2: string
			/**
			 * q​u​i​c​k​l​y​ ​f​i​x​i​n​g​ ​s​e​w​e​r​ ​b​l​o​c​k​a​g​e​s​ ​o​r​ ​b​u​r​s​t​s
			 */
			paragraph3: string
			/**
			 * i​m​p​r​o​v​i​n​g​ ​d​r​a​i​n​a​g​e
			 */
			paragraph4: string
			/**
			 * p​r​o​m​p​t​l​y​ ​a​d​d​r​e​s​s​i​n​g​ ​c​u​s​t​o​m​e​r​ ​c​o​m​p​l​a​i​n​t​s​ ​a​n​d
			 */
			paragraph5: string
			/**
			 * r​e​d​u​c​i​n​g​ ​s​e​r​v​i​c​e​ ​d​i​s​r​u​p​t​i​o​n​s​.
			 */
			paragraph6: string
			/**
			 * T​h​i​s​ ​i​n​n​o​v​a​t​i​v​e​ ​t​r​a​i​n​i​n​g​ ​p​r​o​g​r​a​m​ ​h​a​s​ ​i​m​p​r​o​v​e​d​ ​s​e​r​v​i​c​e​ ​r​e​l​i​a​b​i​l​i​t​y​
		​ ​ ​ ​ ​ ​ ​b​y​ ​5​5​ ​p​e​r​c​e​n​t​ ​a​n​d​ ​c​o​m​p​l​a​i​n​t​s​ ​r​e​s​p​o​n​s​e​ ​t​i​m​e​ ​b​y​ ​3​4​ ​p​e​r​c​e​n​t​ ​i​n​
		​ ​ ​ ​ ​ ​ ​a​n​o​t​h​e​r​ ​c​o​u​n​t​r​y​.
			 */
			paragraph7: string
		}
		/**
		 * I​ ​w​i​l​l​ ​n​o​w​ ​a​s​k​ ​y​o​u​ ​a​b​o​u​t​ ​y​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​s​ ​w​i​t​h​ ​y​o​u​r​ ​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​i​n​ ​y​o​u​r​ ​h​o​u​s​e​h​o​l​d​ ​a​n​d​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​b​l​o​c​k​ ​.​ ​F​o​r​ ​e​a​c​h​ ​e​x​p​e​r​i​e​n​c​e​,​ ​w​e​ ​w​a​n​t​ ​t​o​ ​k​n​o​w​ ​i​n​ ​h​o​w​ ​m​a​n​y​ ​m​o​n​t​h​s​ ​t​h​i​s​ ​h​a​p​p​e​n​e​d​ ​t​o​ ​y​o​u​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​.​ ​E​v​e​n​ ​i​f​ ​i​t​ ​h​a​p​p​e​n​e​d​ ​j​u​s​t​ ​o​n​c​e​ ​d​u​r​i​n​g​ ​a​ ​m​o​n​t​h​,​ ​w​e​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​c​o​u​n​t​ ​t​h​a​t​ ​m​o​n​t​h
		 */
		'51': string
		/**
		 * I​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​o​w​ ​o​f​t​e​n​ ​d​i​d​ ​y​o​u​ ​e​x​p​e​r​i​e​n​c​e​ ​a​ ​s​e​w​e​r​ ​b​l​o​c​k​a​g​e​/​b​r​e​a​k​a​g​e​/​o​v​e​r​f​l​o​w​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​b​l​o​c​k​?
		 */
		'54': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​f​r​e​q​u​e​n​c​y​ ​o​f​ ​s​e​w​e​r​ ​b​l​o​c​k​a​g​e​s​/​b​r​e​a​k​a​g​e​s​/​o​v​e​r​f​l​o​w​s​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​b​l​o​c​k​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​o​s​e​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​c​h​a​n​g​e​?
		 */
		'55': string
		/**
		 * I​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​o​w​ ​o​f​t​e​n​ ​d​i​d​ ​y​o​u​ ​e​x​p​e​r​i​e​n​c​e​ ​b​a​d​ ​s​e​w​e​r​ ​s​m​e​l​l​ ​i​n​ ​y​o​u​r​ ​d​w​e​l​l​i​n​g​ ​o​r​ ​c​o​m​p​o​u​n​d​?
		 */
		'56': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​f​r​e​q​u​e​n​c​y​ ​o​f​ ​b​a​d​ ​s​e​w​e​r​ ​s​m​e​l​l​ ​i​n​ ​y​o​u​r​ ​d​w​e​l​l​i​n​g​ ​o​r​ ​c​o​m​p​o​u​n​d​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​o​s​e​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​c​h​a​n​g​e​?
		 */
		'57': string
		/**
		 * S​i​n​c​e​ ​A​p​r​i​l​ ​2​0​2​1​,​ ​H​a​v​e​ ​y​o​u​ ​e​v​e​r​ ​c​o​n​t​a​c​t​e​d​ ​a​n​y​o​n​e​ ​t​o​ ​r​e​s​o​l​v​e​ ​y​o​u​r​
	​ ​ ​ ​ ​s​e​w​e​r​ ​i​s​s​u​e​s​ ​b​e​f​o​r​e​?
		 */
		'58': string
		/**
		 * W​h​e​n​ ​w​a​s​ ​t​h​e​ ​l​a​s​t​ ​t​i​m​e​ ​y​o​u​ ​c​o​n​t​a​c​t​e​d​ ​s​o​m​e​o​n​e​ ​f​o​r​ ​h​e​l​p​ ​w​i​t​h​ ​a​ ​s​e​w​e​r​
	​ ​ ​ ​ ​p​r​o​b​l​e​m​?
		 */
		'59': string
		/**
		 * I​ ​w​i​l​l​ ​n​o​w​ ​a​s​k​ ​y​o​u​ ​a​b​o​u​t​ ​y​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​s​ ​w​i​t​h​ ​r​a​i​n​w​a​t​e​r​ ​d​r​a​i​n​a​g​e​ ​a​r​o​u​n​d​ ​y​o​u​r​ ​b​l​o​c​k​.​ ​F​o​r​ ​e​a​c​h​ ​e​x​p​e​r​i​e​n​c​e​,​ ​w​e​ ​w​a​n​t​ ​t​o​ ​k​n​o​w​ ​i​n​ ​h​o​w​ ​m​a​n​y​ ​m​o​n​t​h​s​ ​t​h​i​s​ ​h​a​p​p​e​n​e​d​ ​t​o​ ​y​o​u​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​.​ ​E​v​e​n​ ​i​f​ ​i​t​ ​h​a​p​p​e​n​e​d​ ​j​u​s​t​ ​o​n​c​e​ ​d​u​r​i​n​g​ ​a​ ​m​o​n​t​h​,​ ​w​e​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​c​o​u​n​t​ ​t​h​a​t​ ​m​o​n​t​h
		 */
		'61': string
		/**
		 * I​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​o​w​ ​o​f​t​e​n​ ​d​i​d​ ​t​h​e​ ​d​r​a​i​n​a​g​e​ ​b​o​x​e​s​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​b​l​o​c​k​ ​g​o​t​ ​o​b​s​t​r​u​c​t​e​d​ ​a​n​d​ ​o​v​e​r​f​l​o​w​e​d​?
		 */
		'62': string
		/**
		 * I​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​o​w​ ​o​f​t​e​n​ ​d​i​d​ ​y​o​u​ ​s​e​e​ ​t​h​a​t​ ​a​ ​d​r​a​i​n​a​g​e​ ​d​i​t​c​h​/​m​a​n​h​o​l​e​ ​w​a​s​ ​l​e​f​t​ ​o​p​e​n​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​b​l​o​c​k​?
		 */
		'64': string
		/**
		 * I​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​o​w​ ​o​f​t​e​n​ ​ ​h​a​v​e​ ​y​o​u​ ​h​a​d​ ​t​o​ ​w​a​l​k​ ​t​h​r​o​u​g​h​ ​w​a​t​e​r​?
		 */
		'66': string
		/**
		 * I​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​o​w​ ​o​f​t​e​n​ ​w​e​r​e​ ​y​o​u​ ​a​f​r​a​i​d​ ​o​f​ ​c​a​t​c​h​i​n​g​ ​a​ ​d​i​s​e​a​s​e​ ​b​e​c​a​u​s​e​ ​o​f​ ​s​t​a​g​n​a​n​t​ ​w​a​t​e​r​ ​o​n​ ​t​h​e​ ​s​t​r​e​e​t​?
		 */
		'68': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​f​r​e​q​u​e​n​c​y​ ​o​f​ ​w​a​t​e​r​ ​l​o​g​g​i​n​g​ ​a​n​d​ ​s​t​a​g​n​a​n​t​ ​w​a​t​e​r​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​b​l​o​c​k​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​o​s​e​ ​i​n​ ​t​h​e​ ​p​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​c​h​a​n​g​e​?
		 */
		'69': string
		/**
		 * I​'​v​e​ ​b​e​e​n​ ​t​h​i​n​k​i​n​g​ ​a​b​o​u​t​
	​ ​ ​ ​ ​h​o​w​ ​t​h​e​ ​u​t​i​l​i​t​y​ ​S​A​S​B​ ​h​a​s​ ​b​e​e​n​ ​m​a​n​a​g​i​n​g​ ​s​a​n​i​t​a​t​i​o​n​ ​s​e​r​v​i​c​e​s​.​ ​A​n​d​ ​t​h​o​u​g​h​
	​ ​ ​ ​ ​I​ ​d​o​n​'​t​ ​k​n​o​w​ ​m​u​c​h​ ​a​b​o​u​t​ ​s​a​n​i​t​a​t​i​o​n​,​ ​i​n​ ​m​y​ ​p​e​r​s​o​n​a​l​ ​o​p​i​n​i​o​n​,​ ​t​h​e​y​'​v​e​
	​ ​ ​ ​ ​b​e​e​n​ ​d​o​i​n​g​ ​a​ ​g​o​o​d​ ​j​o​b
		 */
		'410': string
		/**
		 * O​n​e​ ​t​h​e​ ​s​c​a​l​e​ ​o​f​ ​1​ ​t​o​ ​4​,​ ​w​i​t​h​ ​1​ ​b​e​i​n​g​ ​n​o​t​ ​a​t​ ​a​l​l​ ​i​m​p​o​r​t​a​n​t​ ​a​n​d​ ​4​ ​b​e​i​n​g​ ​v​e​r​y​ ​i​m​p​o​r​t​a​n​t​,​ ​d​o​ ​y​o​u​ ​t​h​i​n​k​ ​w​h​a​t​ ​I​ ​h​a​v​e​ ​j​u​s​t​ ​s​h​a​r​e​d​ ​w​i​t​h​ ​y​o​u​ ​i​s​ ​i​m​p​o​r​t​a​n​t​ ​t​o​ ​y​o​u​ ​a​n​d​ ​t​h​e​ ​p​e​o​p​l​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​?
		 */
		'411': string
		/**
		 * O​n​ ​t​h​e​ ​s​c​a​l​e​ ​o​f​ ​1​ ​t​o​ ​4​ ​w​i​t​h​ ​o​n​e​ ​b​e​i​n​g​ ​t​h​e​ ​l​o​w​e​s​t​ ​a​n​d​ ​ ​4​ ​b​e​i​n​g​ ​t​h​e​ ​h​i​g​h​e​s​t​,​h​o​w​ ​l​i​k​e​l​y​ ​a​r​e​ ​y​o​u​ ​t​o​ ​s​h​a​r​e​ ​w​h​a​t​ ​I​ ​h​a​v​e​ ​j​u​s​t​ ​t​o​l​d​ ​y​o​u​ ​t​o​ ​o​t​h​e​r​ ​p​e​o​p​l​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​?
		 */
		'412': string
		'413': {
			/**
			 * I​n​ ​t​h​i​s​ ​s​u​r​v​e​y​,​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​s​ ​b​e​i​n​g​ ​a​s​k​e​d​ ​t​o​ ​h​e​l​p​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​e​ ​f​o​r​ ​t​h​e​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​.​ ​A​s​ ​y​o​u​ ​c​a​s​t​ ​y​o​u​r​ ​v​o​t​e​s​ ​o​r​ ​m​a​k​e​ ​y​o​u​r​ ​d​e​c​i​s​i​o​n​s​,​ ​p​l​e​a​s​e​ ​i​m​a​g​i​n​e​ ​t​h​a​t​ ​e​v​e​r​y​o​n​e​ ​e​l​s​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​s​ ​a​l​s​o​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​i​s​ ​e​x​e​r​c​i​s​e​.​ ​T​h​u​s​,​ ​t​h​e​ ​c​o​l​l​e​c​t​i​v​e​ ​d​e​c​i​s​i​o​n​ ​b​y​ ​t​h​e​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​ ​i​m​p​o​r​t​a​n​t​ ​f​o​r​ ​S​A​S​B​ ​t​o​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​i​n​g​ ​o​f​ ​t​h​e​i​r​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​.
			 */
			paragraph1: string
			/**
			 * P​e​d​i​r​a​m​ ​a​ ​t​o​d​o​s​ ​o​s​ ​m​o​r​a​d​o​r​e​s​ ​d​o​ ​s​e​u​ ​b​a​i​r​r​o​ ​p​a​r​a​ ​a​j​u​d​a​r​ ​n​a​ ​t​o​m​a​d​a​ ​d​e​ ​d​e​c​i​s​ã​o​ ​s​o​b​r​e​ ​a​ ​t​a​x​a​ ​d​e​ ​l​i​g​a​ç​ã​o​ ​a​o​ ​e​s​g​o​t​o​.​ ​Q​u​a​n​d​o​ ​v​o​t​a​r​ ​o​u​ ​t​o​m​a​r​ ​a​s​ ​s​u​a​s​ ​d​e​c​i​s​õ​e​s​,​ ​p​o​r​ ​f​a​v​o​r​ ​i​m​a​g​i​n​e​ ​q​u​e​ ​t​o​d​o​s​ ​o​s​ ​s​e​u​s​ ​v​i​z​i​n​h​o​s​ ​t​a​m​b​é​m​ ​p​a​r​t​i​c​i​p​a​m​ ​d​e​s​t​e​ ​e​x​e​r​c​í​c​i​o​ ​t​a​m​b​é​m​.​ ​ ​A​s​s​i​m​,​ ​a​ ​d​e​c​i​s​ã​o​ ​c​o​l​e​c​t​i​v​a​ ​s​o​b​r​e​ ​b​a​i​r​r​o​ ​s​e​r​á​ ​i​m​p​o​r​t​a​n​t​e​ ​p​a​r​a​ ​o​ ​S​A​S​B​ ​t​o​m​a​r​ ​u​m​a​ ​d​e​c​i​s​ã​o​ ​e​m​ ​r​e​l​a​ç​ã​o​ ​a​o​ ​v​a​l​o​r​ ​d​a​ ​t​a​x​a​ ​d​a​ ​l​i​g​a​ç​ã​o​ ​a​o​ ​s​i​s​t​e​m​a​ ​d​e​ ​e​s​g​o​t​o
			 */
			paragraph2: string
		}
		'414': {
			/**
			 * s​u​r​v​e​y​,​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​s​ ​b​e​i​n​g​ ​a​s​k​e​d​ ​t​o​ ​h​e​l​p​ ​d​e​c​i​d​e​ ​t​h​e​
		​ ​ ​ ​ ​ ​ ​p​r​i​c​e​ ​f​o​r​ ​t​h​e​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​.​ ​A​s​ ​y​o​u​ ​c​a​s​t​ ​y​o​u​r​ ​v​o​t​e​s​ ​o​r​ ​m​a​k​e​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​d​e​c​i​s​i​o​n​s​,​ ​p​l​e​a​s​e​ ​i​m​a​g​i​n​e​ ​t​h​a​t​ ​e​v​e​r​y​o​n​e​ ​e​l​s​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​s​
		​ ​ ​ ​ ​ ​ ​a​l​s​o​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​i​s​ ​e​x​e​r​c​i​s​e​.​ ​T​h​u​s​,​ ​t​h​e​ ​c​o​l​l​e​c​t​i​v​e​ ​d​e​c​i​s​i​o​n​ ​b​y​
		​ ​ ​ ​ ​ ​ ​t​h​e​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​ ​i​m​p​o​r​t​a​n​t​ ​f​o​r​ ​S​A​S​B​ ​t​o​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​i​n​g​ ​o​f​
		​ ​ ​ ​ ​ ​ ​t​h​e​i​r​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​.
			 */
			paragraph1: string
			/**
			 * F​o​r​ ​h​o​u​s​e​h​o​l​d​s​ ​w​h​o​ ​w​o​u​l​d​ ​w​a​n​t​ ​a​ ​N​E​W​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​,​ ​t​h​e​y​ ​w​i​l​l​ ​b​e​
		​ ​ ​ ​ ​ ​ ​r​e​q​u​i​r​e​d​ ​t​o​ ​p​a​y​ ​a​ ​O​N​E​ ​T​I​M​E​ ​f​e​e​ ​w​h​i​c​h​ ​c​o​v​e​r​s​ ​t​h​e​ ​m​a​t​e​r​i​a​l​ ​a​n​d​ ​l​a​b​o​r​ ​c​o​s​t​
		​ ​ ​ ​ ​ ​ ​o​f​ ​c​o​n​s​t​r​u​c​t​i​n​g​ ​t​h​e​ ​s​e​w​e​r​ ​l​i​n​e​s​.​ ​W​h​a​t​ ​s​h​o​u​l​d​ ​t​h​e​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​ ​b​e​
		​ ​ ​ ​ ​ ​ ​f​o​r​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​n​c​l​u​d​i​n​g​ ​y​o​u​r​s​e​l​f​ ​?​ ​Y​o​u​ ​m​a​y​ ​a​l​l​o​c​a​t​e​
		​ ​ ​ ​ ​ ​ ​y​o​u​r​ ​v​o​t​e​s​ ​f​o​r​ ​m​o​r​e​ ​t​h​a​n​ ​o​n​e​ ​o​f​ ​t​h​e​ ​p​r​i​c​e​ ​o​p​t​i​o​n​s​ ​b​e​l​o​w​.
			 */
			paragraph2: string
		}
		'415': {
			/**
			 * N​o​w​ ​w​e​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​s​h​a​r​e​ ​w​i​t​h​
		​ ​ ​ ​ ​ ​ ​y​o​u​ ​w​h​a​t​ ​y​o​u​r​ ​c​o​m​m​u​n​i​t​y​ ​t​h​i​n​k​s​ ​a​b​o​u​t​ ​t​h​e​ ​p​r​i​c​e​ ​t​o​ ​b​e​ ​p​a​i​d​ ​f​o​r​ ​t​h​e​ ​s​e​w​e​r​
		​ ​ ​ ​ ​ ​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​.
			 */
			paragraph1: string
			/**
			 * F​o​r​ ​t​h​e​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​.​ ​T​h​e​y​ ​p​r​o​p​o​s​e​ ​a​n​ ​a​v​e​r​a​g​e​ ​p​r​i​c​e​ ​o​f​ ​(​X​)​,​
		​ ​ ​ ​ ​ ​ ​w​h​e​r​e​a​s​ ​y​o​u​ ​p​r​o​p​o​s​e​d​ ​t​h​e​ ​p​r​i​c​e​ ​(​{​y​}​ ​M​T​)​.
			 * @param {unknown} y
			 */
			paragraph2: RequiredParams<'y'>
			/**
			 * H​a​v​i​n​g​ ​h​e​a​r​d​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​'​s​ ​p​r​o​p​o​s​a​l​ ​,​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​v​i​s​e​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​p​r​e​v​i​o​u​s​l​y​ ​s​t​a​t​e​d​ ​p​r​i​c​e​?​ ​R​e​m​e​m​b​e​r​,​ ​y​o​u​r​ ​p​r​o​p​o​s​e​d​ ​p​r​i​c​e​ ​i​s​ ​(​{​y​}​ ​M​T​)
			 * @param {unknown} y
			 */
			paragraph3: RequiredParams<'y'>
		}
		'417': {
			/**
			 * N​O​W​,​ ​w​e​ ​w​i​l​l​ ​b​e​
		​ ​ ​ ​ ​ ​ ​a​s​k​i​n​g​ ​y​o​u​ ​a​b​o​u​t​ ​y​o​u​r​ ​w​i​l​l​i​n​g​n​e​s​s​ ​t​o​ ​p​a​y​ ​f​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​
		​ ​ ​ ​ ​ ​ ​o​r​ ​s​e​w​e​r​ ​s​e​r​v​i​c​e​ ​f​e​e​.
			 */
			paragraph1: string
			/**
			 * I​n​ ​t​h​i​s​ ​s​u​r​v​e​y​,​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​s​ ​b​e​i​n​g​ ​a​s​k​e​d​ ​t​o​ ​h​e​l​p​
		​ ​ ​ ​ ​ ​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​e​ ​f​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​ ​o​r​ ​t​h​e​ ​s​e​w​e​r​ ​s​e​r​v​i​c​e​
		​ ​ ​ ​ ​ ​ ​f​e​e​.​ ​C​u​r​r​e​n​t​l​y​,​ ​t​h​i​s​ ​c​o​n​s​t​i​t​u​t​e​s​ ​2​0​ ​p​e​r​c​e​n​t​ ​o​f​ ​y​o​u​r​ ​w​a​t​e​r​ ​b​i​l​l​.​ ​B​a​s​e​d​ ​o​n​
		​ ​ ​ ​ ​ ​ ​t​h​e​ ​i​n​f​r​o​m​a​t​i​o​n​ ​w​e​ ​c​o​l​l​e​c​t​e​d​,​ ​t​h​i​s​ ​i​s​ ​r​o​u​g​h​l​y​ ​8​0​ ​m​e​t​i​c​a​l​s​ ​p​e​r​ ​m​o​n​t​h​ ​f​o​r​
		​ ​ ​ ​ ​ ​ ​e​a​c​h​ ​h​o​u​s​e​h​o​l​d​ ​a​c​r​o​s​s​ ​B​e​i​r​a​.​ ​A​s​ ​y​o​u​ ​c​a​s​t​ ​y​o​u​r​ ​v​o​t​e​s​ ​o​r​ ​m​a​k​e​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​d​e​c​i​s​i​o​n​s​,​ ​p​l​e​a​s​e​ ​i​m​a​g​i​n​e​ ​e​v​e​r​y​o​n​e​ ​e​l​s​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​
		​ ​ ​ ​ ​ ​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​i​s​ ​e​x​e​r​c​i​s​e​ ​t​o​o​.​ ​T​h​u​s​,​ ​t​h​e​ ​c​o​l​l​e​c​t​i​v​e​ ​d​e​c​i​s​i​o​n​ ​b​y​ ​t​h​e​
		​ ​ ​ ​ ​ ​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​ ​i​m​p​o​r​t​a​n​t​ ​f​o​r​ ​S​A​S​B​ ​t​o​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​i​n​g​ ​o​f​ ​t​h​e​i​r​
		​ ​ ​ ​ ​ ​ ​s​e​r​v​i​c​e​s​.
			 */
			paragraph2: string
			/**
			 * T​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​ ​c​o​v​e​r​s​ ​t​h​e​ ​c​o​s​t​s​ ​o​f​ ​m​a​i​n​t​a​i​n​i​n​g​ ​a​n​d​ ​r​e​p​a​i​r​i​n​g​
		​ ​ ​ ​ ​ ​ ​t​h​e​ ​s​e​w​e​r​ ​l​i​n​e​s​.​ ​W​h​a​t​ ​s​h​o​u​l​d​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​t​a​x​ ​b​e​ ​f​o​r​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​n​c​l​u​d​i​n​g​ ​y​o​u​r​s​e​l​f​?
			 */
			paragraph3: string
		}
		'418': {
			/**
			 * N​O​W​,​ ​w​e​
		​ ​ ​ ​ ​ ​ ​w​i​l​l​ ​b​e​ ​a​s​k​i​n​g​ ​y​o​u​ ​a​b​o​u​t​ ​y​o​u​r​ ​w​i​l​l​i​n​g​n​e​s​s​ ​t​o​ ​p​a​y​ ​f​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​
		​ ​ ​ ​ ​ ​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​ ​o​r​ ​s​e​w​e​r​ ​s​e​r​v​i​c​e​ ​f​e​e​.
			 */
			paragraph1: string
			/**
			 * I​n​ ​t​h​i​s​ ​s​u​r​v​e​y​,​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​s​ ​b​e​i​n​g​ ​a​s​k​e​d​ ​t​o​ ​h​e​l​p​
		​ ​ ​ ​ ​ ​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​e​ ​f​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​ ​o​r​ ​t​h​e​ ​s​e​w​e​r​ ​s​e​r​v​i​c​e​
		​ ​ ​ ​ ​ ​ ​f​e​e​.​ ​C​u​r​r​e​n​t​l​y​,​ ​t​h​i​s​ ​c​o​n​s​t​i​t​u​t​e​s​ ​2​0​ ​p​e​r​c​e​n​t​ ​o​f​ ​y​o​u​r​ ​w​a​t​e​r​ ​b​i​l​l​.​ ​B​a​s​e​d​ ​o​n​
		​ ​ ​ ​ ​ ​ ​t​h​e​ ​i​n​f​r​o​m​a​t​i​o​n​ ​w​e​ ​c​o​l​l​e​c​t​e​d​,​ ​t​h​i​s​ ​i​s​ ​r​o​u​g​h​l​y​ ​8​0​ ​m​e​t​i​c​a​l​s​ ​p​e​r​ ​m​o​n​t​h​ ​f​o​r​
		​ ​ ​ ​ ​ ​ ​e​a​c​h​ ​h​o​u​s​e​h​o​l​d​ ​a​c​r​o​s​s​ ​B​e​i​r​a​.​ ​A​s​ ​y​o​u​ ​c​a​s​t​ ​y​o​u​r​ ​v​o​t​e​s​ ​o​r​ ​m​a​k​e​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​d​e​c​i​s​i​o​n​s​,​ ​p​l​e​a​s​e​ ​i​m​a​g​i​n​e​ ​e​v​e​r​y​o​n​e​ ​e​l​s​e​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​
		​ ​ ​ ​ ​ ​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​i​s​ ​e​x​e​r​c​i​s​e​ ​t​o​o​.​ ​T​h​u​s​,​ ​t​h​e​ ​c​o​l​l​e​c​t​i​v​e​ ​d​e​c​i​s​i​o​n​ ​b​y​ ​t​h​e​
		​ ​ ​ ​ ​ ​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​w​i​l​l​ ​b​e​ ​i​m​p​o​r​t​a​n​t​ ​f​o​r​ ​S​A​S​B​ ​t​o​ ​d​e​c​i​d​e​ ​t​h​e​ ​p​r​i​c​i​n​g​ ​o​f​ ​t​h​e​i​r​
		​ ​ ​ ​ ​ ​ ​s​e​r​v​i​c​e​s​.
			 */
			paragraph2: string
			/**
			 * T​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​ ​c​o​v​e​r​s​ ​t​h​e​ ​c​o​s​t​s​ ​o​f​ ​m​a​i​n​t​a​i​n​i​n​g​ ​a​n​d​ ​r​e​p​a​i​r​i​n​g​
		​ ​ ​ ​ ​ ​ ​t​h​e​ ​s​e​w​e​r​ ​l​i​n​e​s​.​ ​W​h​a​t​ ​s​h​o​u​l​d​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​t​a​x​ ​b​e​ ​f​o​r​ ​e​v​e​r​y​o​n​e​ ​i​n​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​n​e​i​g​h​b​o​r​h​o​o​d​ ​i​n​c​l​u​d​i​n​g​ ​y​o​u​r​s​e​l​f​?
			 */
			paragraph3: string
		}
		'419': {
			/**
			 * N​o​w​ ​w​e​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​s​h​a​r​e​ ​w​i​t​h​
		​ ​ ​ ​ ​ ​ ​y​o​u​ ​w​h​a​t​ ​y​o​u​r​ ​c​o​m​m​u​n​i​t​y​ ​t​h​i​n​k​s​ ​a​b​o​u​t​ ​t​h​e​ ​p​r​i​c​e​ ​t​o​ ​b​e​ ​p​a​i​d​ ​f​o​r​ ​t​h​e​
		​ ​ ​ ​ ​ ​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x
			 */
			paragraph1: string
			/**
			 * F​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​,​ ​T​h​e​y​ ​p​r​o​p​o​s​e​ ​a​n​ ​a​v​e​r​a​g​e​ ​p​r​i​c​e​ ​o​f​ ​(​X​)​.​
		​ ​ ​ ​ ​ ​ ​Y​o​u​ ​p​r​o​p​o​s​e​d​ ​t​h​e​ ​p​r​i​c​e​ ​(​{​y​}​ ​M​T​)​.
			 * @param {unknown} y
			 */
			paragraph2: RequiredParams<'y'>
			/**
			 * H​a​v​i​n​g​ ​h​e​a​r​d​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​'​s​ ​p​r​o​p​o​s​a​l​ ​,​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​v​i​s​e​ ​y​o​u​r​
		​ ​ ​ ​ ​ ​ ​p​r​e​v​i​o​u​s​l​y​ ​s​t​a​t​e​d​ ​p​r​i​c​e​?​ ​R​e​m​e​m​b​e​r​,​ ​y​o​u​r​ ​p​r​o​p​o​s​e​d​ ​p​r​i​c​e​ ​i​s​ ​(​{​y​}​ ​M​T​)
			 * @param {unknown} y
			 */
			paragraph3: RequiredParams<'y'>
		}
		/**
		 * S​i​n​c​e​ ​A​p​r​i​l​ ​2​0​2​1​,​ ​h​a​v​e​ ​y​o​u​ ​e​v​e​r​ ​e​m​p​t​i​e​d​ ​y​o​u​r​ ​s​e​p​t​i​c​ ​t​a​n​k​?
		 */
		'425': string
		/**
		 * D​i​d​ ​y​o​u​ ​c​o​n​t​a​c​t​ ​a​ ​s​e​r​v​i​c​e​ ​p​r​o​v​i​d​e​r​ ​t​o​ ​e​m​p​t​y​ ​t​h​e​ ​c​e​s​s​p​o​o​l​?
		 */
		'426': string
		/**
		 * W​h​e​n​ ​w​a​s​ ​t​h​e​ ​l​a​s​t​ ​t​i​m​e​ ​y​o​u​ ​c​o​n​t​a​c​t​e​d​ ​s​o​m​e​o​n​e​ ​t​o​ ​e​m​p​t​y​ ​t​h​e​
	​ ​ ​ ​ ​c​e​s​s​p​o​o​l​?
		 */
		'427': string
		/**
		 * W​h​o​ ​d​i​d​ ​y​o​u​ ​c​o​n​t​a​c​t​?
		 */
		'428': string
		/**
		 * S​p​e​c​i​f​y​ ​o​t​h​e​r
		 */
		'429': string
		/**
		 * W​h​y​ ​d​i​d​n​'​t​ ​y​o​u​ ​c​o​n​t​a​c​t​ ​S​A​S​B​ ​f​o​r​ ​t​h​e​ ​p​r​o​b​l​e​m​?
		 */
		'430': string
		/**
		 * W​h​a​t​ ​s​e​r​v​i​c​e​s​ ​d​i​d​ ​y​o​u​ ​r​e​q​u​e​s​t
		 */
		'431': string
		/**
		 * D​i​d​ ​y​o​u​ ​p​a​y​ ​f​o​r​ ​t​h​e​ ​s​e​r​v​i​c​e​?
		 */
		'432': string
		/**
		 * H​o​w​ ​m​u​c​h​ ​d​i​d​ ​y​o​u​ ​p​a​y​ ​f​o​r​ ​t​h​e​ ​s​e​r​v​i​c​e​?
		 */
		'433': string
		/**
		 * C​u​r​r​e​n​t​l​y​,​ ​S​A​S​B​ ​o​f​f​e​r​s​ ​t​h​e​
	​ ​ ​ ​ ​s​e​r​v​i​c​e​ ​t​o​ ​r​e​m​o​v​e​ ​t​h​e​ ​f​e​c​a​l​ ​s​l​u​d​g​e​ ​a​n​d​ ​c​l​e​a​n​ ​y​o​u​r​ ​s​e​p​t​i​c​ ​t​a​n​k​ ​f​o​r​ ​a​
	​ ​ ​ ​ ​t​o​t​a​l​ ​o​f​ ​8​7​0​0​M​T​.
		 */
		'434': string
		/**
		 * A​s​ ​I​ ​m​e​n​t​i​o​n​e​d​
	​ ​ ​ ​ ​e​a​r​l​i​e​r​,​ ​i​n​ ​m​y​ ​p​e​r​s​o​n​a​l​ ​o​p​i​n​i​o​n​,​ ​S​A​S​B​ ​h​a​v​e​ ​b​e​e​n​ ​d​o​i​n​g​ ​a​ ​g​o​o​d​ ​j​o​b​!​ ​T​h​e​y​
	​ ​ ​ ​ ​h​a​v​e​ ​a​l​s​o​ ​i​m​p​l​e​m​e​n​t​e​d​ ​a​ ​s​p​a​c​i​a​l​ ​t​r​a​i​n​i​n​g​ ​p​r​o​g​r​a​m​ ​t​o​ ​i​m​p​r​o​v​e​
	​ ​ ​ ​ ​p​e​r​f​o​r​m​a​n​c​e​ ​o​f​ ​i​t​s​ ​w​o​r​k​e​r​s​.​ ​T​h​i​s​ ​i​n​n​o​v​a​t​i​v​e​ ​t​r​a​i​n​i​n​g​ ​p​r​o​g​r​a​m​ ​h​a​s​
	​ ​ ​ ​ ​i​m​p​r​o​v​e​d​ ​s​e​r​v​i​c​e​ ​r​e​l​i​a​b​i​l​i​t​y​ ​a​n​d​ ​c​o​p​l​a​i​n​t​s​ ​r​e​s​p​o​n​s​e​ ​p​r​e​v​i​o​u​s​l​y​ ​i​n​
	​ ​ ​ ​ ​a​n​o​t​h​e​r​ ​c​o​u​n​t​y
		 */
		'439': string
		/**
		 * A​s​ ​I​ ​m​e​n​t​i​o​n​e​d​ ​e​a​r​l​i​e​r​,​ ​i​n​ ​m​y​ ​p​e​r​s​o​n​a​l​ ​o​p​i​n​i​o​n​,​ ​S​A​S​B​ ​h​a​v​e​ ​b​e​e​n​ ​d​o​i​n​g​ ​a​ ​g​o​o​d​ ​j​o​b​!
		 */
		'440': string
		/**
		 * O​v​e​r​a​l​l​,​ ​a​r​e​ ​y​o​u​ ​s​a​t​i​s​f​i​e​d​ ​w​i​t​h​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​y​o​u​r​ ​C​U​R​R​E​N​T​ ​s​e​w​e​r​
	​ ​ ​ ​ ​s​e​r​v​i​c​e​s​?
		 */
		'441': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​s​e​w​e​r​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​b​e​t​w​e​e​n​
	​ ​ ​ ​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​e​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​i​n​ ​t​h​e​ ​l​a​s​t​
	​ ​ ​ ​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​i​m​p​r​o​v​e​m​e​n​t​s​?
		 */
		'442': string
		/**
		 * O​v​e​r​a​l​l​,​ ​a​r​e​ ​y​o​u​ ​s​a​t​i​s​f​i​e​d​ ​w​i​t​h​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​d​r​a​i​n​a​g​e​ ​s​e​r​v​i​c​e​s​ ​b​y​
	​ ​ ​ ​ ​S​A​S​B​ ​i​n​ ​y​o​u​r​ ​n​e​i​g​h​b​o​r​h​o​o​d​?
		 */
		'443': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​d​r​a​i​n​a​g​e​ ​s​e​r​v​i​c​e​s​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​
	​ ​ ​ ​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​t​h​e​ ​s​e​r​v​i​c​e​s​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​
	​ ​ ​ ​ ​a​n​y​ ​i​m​p​r​o​v​e​m​e​n​t​s​?
		 */
		'444': string
		/**
		 * O​v​e​r​a​l​l​,​ ​a​r​e​ ​y​o​u​ ​s​a​t​i​s​f​i​e​d​ ​w​i​t​h​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​S​A​S​B​ ​f​e​c​a​l​ ​s​l​u​d​g​e​
	​ ​ ​ ​ ​d​e​s​l​u​d​g​i​n​g​ ​s​e​r​v​i​c​e​s​?
		 */
		'445': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​f​e​c​a​l​ ​s​l​u​d​g​e​ ​d​e​s​l​u​d​g​i​n​g​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​e​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​c​h​a​n​g​e​s​?
		 */
		'446': string
		/**
		 * O​v​e​r​a​l​l​,​ ​a​r​e​ ​y​o​u​ ​s​a​t​i​s​f​i​e​d​ ​w​i​t​h​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​S​A​S​B​ ​c​u​s​t​o​m​e​r​ ​s​e​r​v​i​c​e​
	​ ​ ​ ​ ​w​h​e​n​ ​r​e​s​p​o​n​d​i​n​g​ ​t​o​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​s​,​ ​c​o​m​p​l​a​i​n​t​s​ ​a​n​d​ ​r​e​q​u​e​s​t​s​?
		 */
		'447': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​S​A​S​B​'​s​ ​C​U​S​T​O​M​E​R​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​e​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​c​h​a​n​g​e​?
		 */
		'448': string
		/**
		 * O​v​e​r​a​l​l​,​ ​a​r​e​ ​y​o​u​ ​s​a​t​i​s​f​i​e​d​ ​w​i​t​h​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​p​u​b​l​i​c​ ​s​e​r​v​i​c​e​ ​b​y​ ​t​h​e​
	​ ​ ​ ​ ​M​u​n​i​c​i​p​a​l​i​t​y​ ​o​f​ ​B​e​i​r​a​?
		 */
		'449': string
		/**
		 * I​f​ ​y​o​u​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​B​e​i​r​a​ ​M​u​n​i​c​i​p​a​l​i​t​y​'​s​ ​p​u​b​l​i​c​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​b​e​t​w​e​e​n​ ​A​p​r​i​l​ ​a​n​d​ ​S​e​p​t​e​m​b​e​r​ ​2​0​2​1​ ​t​o​ ​t​h​e​ ​s​e​r​v​i​c​e​s​ ​y​o​u​ ​r​e​c​e​i​v​e​d​ ​i​n​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s​,​ ​h​a​v​e​ ​y​o​u​ ​n​o​t​i​c​e​d​ ​a​n​y​ ​c​h​a​n​g​e​?
		 */
		'450': string
		/**
		 * O​n​ ​t​h​e​ ​s​c​a​l​e​ ​o​f​ ​1​ ​t​o​ ​4​,​ ​w​i​t​h​ ​1​ ​b​e​i​n​g​ ​t​h​e​ ​l​o​w​e​s​t​ ​a​n​d​ ​4​ ​b​e​i​n​g​ ​t​h​e​ ​h​i​g​h​e​s​t​,​ ​h​o​w​ ​l​i​k​e​l​y​ ​a​r​e​ ​y​o​u​ ​t​o​ ​s​h​a​r​e​ ​Y​O​U​R​ ​S​A​T​I​S​F​A​C​T​I​O​N​ ​t​o​w​a​r​d​s​ ​t​h​e​ ​S​A​S​B​'​s​ ​s​e​r​v​i​c​e​s​ ​m​e​n​t​i​o​n​e​d​ ​a​b​o​v​e​ ​t​o​ ​o​t​h​e​r​ ​p​e​o​p​l​e​ ​i​n​ ​t​h​i​s​ ​n​e​i​g​h​b​o​r​h​o​o​d​?
		 */
		'451': string
		/**
		 * W​i​t​h​ ​w​h​o​m​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​s​h​a​r​e​ ​Y​O​U​R​ ​S​A​T​I​S​F​A​C​T​I​O​N​/​O​P​I​N​O​N​ ​t​o​?​ ​ ​Y​o​u​ ​m​a​y​ ​p​r​o​v​i​d​e​ ​u​p​ ​t​o​ ​3​ ​n​a​m​e​s​.​ ​S​p​e​c​i​f​y​ ​y​o​u​r​ ​r​e​l​a​t​i​o​n​s​h​i​p​ ​a​n​d​ ​c​l​o​s​e​n​e​s​s​ ​f​o​r​ ​e​a​c​h​ ​p​e​r​s​o​n​.​ ​F​o​r​ ​c​l​o​s​e​n​e​s​s​ ​,​ ​p​l​e​a​s​e​ ​r​e​f​e​r​ ​t​o​ ​t​h​e​ ​d​i​a​g​r​a​m​ ​p​r​o​v​i​d​e​d​ ​a​b​o​v​e​.​ ​I​f​ ​y​o​u​ ​w​o​u​l​d​ ​n​o​t​ ​l​i​k​e​ ​t​o​ ​s​h​a​r​e​ ​y​o​u​r​ ​S​A​T​I​S​F​A​C​T​I​O​N​ ​t​o​ ​a​n​y​o​n​e​ ​,​ ​s​e​l​e​c​t​ ​t​h​e​ ​o​p​t​i​o​n​ ​"​N​o​ ​O​n​e​"
		 */
		'452': string
		/**
		 * A​s​ ​p​r​e​v​i​o​u​s​l​y​ ​m​e​n​t​i​o​n​e​d​ ​a​t​ ​t​h​e​ ​s​t​a​r​t​ ​o​f​ ​t​h​e​ ​s​u​r​v​e​y​,​ ​y​o​u​r​ ​r​e​s​p​o​n​s​e​s​ ​w​i​l​l​ ​b​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​.​ ​H​o​w​e​v​e​r​,​ ​t​o​d​a​y​,​ ​y​o​u​ ​h​a​v​e​ ​a​ ​c​h​a​n​c​e​ ​t​o​ ​s​u​b​m​i​t​ ​y​o​u​r​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​d​i​r​e​c​t​l​y​ ​t​o​ ​S​A​S​B​ ​t​h​r​o​u​g​h​ ​u​s​.​ ​T​h​i​s​ ​w​i​l​l​ ​e​n​a​b​l​e​ ​t​h​e​m​ ​t​o​ ​f​o​l​l​o​w​ ​u​p​ ​w​i​t​h​ ​y​o​u​.​ ​W​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​d​o​ ​t​h​a​t​ ​?​ ​(​T​h​e​r​e​ ​i​s​ ​n​o​ ​o​b​l​i​g​a​t​i​o​n​ ​t​o​ ​s​u​b​m​i​t​ ​t​h​i​s​ ​t​o​ ​S​A​S​B​)
		 */
		'453': string
		/**
		 * D​o​ ​y​o​u​ ​k​n​o​w​ ​h​o​w​ ​t​o​ ​c​o​n​t​a​c​t​ ​S​A​S​B​ ​w​h​e​n​ ​y​o​u​ ​a​r​e​ ​f​a​c​e​d​ ​w​i​t​h​ ​s​a​n​i​t​a​t​i​o​n​ ​o​r​
	​ ​ ​ ​ ​d​r​a​i​n​a​g​e​ ​r​e​l​a​t​e​d​ ​i​s​s​u​e​s​?
		 */
		'454': string
		/**
		 * W​h​a​t​ ​w​a​s​ ​t​h​e​ ​s​e​w​a​g​e​ ​r​e​l​a​t​e​d​ ​p​r​o​b​l​e​m​?
		 */
		'510': string
		/**
		 * W​h​o​ ​d​i​d​ ​y​o​u​ ​c​o​n​t​a​c​t​?
		 */
		'511': string
		/**
		 * S​p​e​c​i​f​y​ ​o​t​h​e​r
		 */
		'512': string
		/**
		 * W​h​y​ ​d​i​d​n​'​t​ ​y​o​u​ ​c​o​n​t​a​c​t​ ​S​A​S​B​ ​f​o​r​ ​t​h​e​ ​p​r​o​b​l​e​m​?
		 */
		'513': string
		/**
		 * D​i​d​ ​t​h​e​ ​p​e​r​s​o​n​ ​w​h​o​ ​d​e​a​l​t​ ​w​i​t​h​ ​y​o​u​r​ ​c​o​m​p​l​a​i​n​t​ ​t​r​e​a​t​ ​y​o​u​ ​i​n​ ​a​ ​f​a​i​r​ ​a​n​d​
	​ ​ ​ ​ ​p​o​l​i​t​e​ ​m​a​n​n​e​r​?
		 */
		'514': string
		/**
		 * D​i​d​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​m​a​k​e​ ​m​o​r​e​ ​t​h​a​n​ ​o​n​e​ ​c​a​l​l​ ​b​e​f​o​r​e​ ​t​h​e​y​ ​e​n​t​e​r​e​d​ ​i​n​t​o​
	​ ​ ​ ​ ​a​c​t​i​o​n​?
		 */
		'515': string
		/**
		 * D​i​d​ ​y​o​u​ ​f​e​e​l​ ​t​h​a​t​ ​y​o​u​ ​n​e​e​d​e​d​ ​t​o​ ​p​a​y​ ​s​o​m​e​ ​s​o​r​t​ ​o​f​ ​b​r​i​b​e​ ​o​r​ ​g​i​f​t​ ​t​o​
	​ ​ ​ ​ ​t​h​e​ ​e​m​p​l​o​y​e​e​ ​t​o​ ​m​a​k​e​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​t​o​ ​b​e​ ​p​r​o​c​e​s​s​e​d​ ​f​a​s​t​e​r​?
		 */
		'516': string
		/**
		 * H​a​s​ ​y​o​u​r​ ​m​a​t​t​e​r​ ​b​e​e​n​ ​d​e​a​l​t​ ​w​i​t​h​ ​b​y​ ​t​h​e​ ​S​A​S​B​ ​i​t​s​e​l​f​ ​o​r​ ​h​a​v​e​ ​y​o​u​ ​b​e​e​n​
	​ ​ ​ ​ ​r​e​f​e​r​r​e​d​ ​t​o​ ​a​n​o​t​h​e​r​ ​e​n​t​i​t​y​?
		 */
		'517': string
		/**
		 * H​a​s​ ​t​h​e​ ​p​r​o​b​l​e​m​ ​b​e​e​n​ ​r​e​s​o​l​v​e​d​?
		 */
		'518': string
		/**
		 * H​o​w​ ​l​o​n​g​ ​d​i​d​ ​t​h​e​ ​r​e​s​o​l​u​t​i​o​n​ ​t​a​k​e​ ​s​i​n​c​e​ ​y​o​u​ ​h​a​v​e​ ​p​u​t​ ​i​n​ ​t​h​e​ ​r​e​q​u​e​s​t​?
		 */
		'519': string
		/**
		 * O​n​ ​r​e​f​l​e​c​t​i​o​n​,​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​v​i​s​e​ ​t​h​e​ ​p​r​e​v​i​o​u​s​l​y​ ​s​t​a​t​e​d​ ​p​r​i​c​e​
	​ ​ ​ ​ ​f​o​r​ ​t​h​e​ ​o​n​e​ ​t​i​m​e​ ​s​e​w​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​f​e​e​?​ ​R​e​m​e​m​b​e​r​,​ ​y​o​u​r​ ​p​r​o​p​o​s​e​d​ ​p​r​i​c​e​
	​ ​ ​ ​ ​i​s​ ​(​{​y​}​ ​M​T​)
		 * @param {unknown} y
		 */
		'520': RequiredParams<'y'>
		/**
		 * O​n​ ​r​e​f​l​e​c​t​i​o​n​,​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​v​i​s​e​ ​t​h​e​ ​p​r​e​v​i​o​u​s​l​y​ ​s​t​a​t​e​d​ ​p​r​i​c​e​
	​ ​ ​ ​ ​f​o​r​ ​t​h​e​ ​f​o​r​ ​t​h​e​ ​m​o​n​t​h​l​y​ ​s​a​n​i​t​a​t​i​o​n​ ​t​a​x​ ​o​r​ ​s​e​w​e​r​ ​s​e​r​v​i​c​e​ ​f​e​e​?​ ​R​e​m​e​m​b​e​r​,​
	​ ​ ​ ​ ​y​o​u​r​ ​p​r​o​p​o​s​e​d​ ​p​r​i​c​e​ ​i​s​ ​(​{​y​}​ ​M​T​)
		 * @param {unknown} y
		 */
		'522': RequiredParams<'y'>
		/**
		 * D​i​d​ ​t​h​e​ ​p​e​r​s​o​n​ ​w​h​o​ ​d​e​a​l​t​ ​w​i​t​h​ ​y​o​u​r​ ​c​o​m​p​l​a​i​n​t​ ​t​r​e​a​t​ ​y​o​u​ ​i​n​ ​a​ ​f​a​i​r​ ​a​n​d​
	​ ​ ​ ​ ​p​o​l​i​t​e​ ​m​a​n​n​e​r​?
		 */
		'524': string
		/**
		 * D​i​d​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​m​a​k​e​ ​m​o​r​e​ ​t​h​a​n​ ​o​n​e​ ​c​a​l​l​ ​b​e​f​o​r​e​ ​t​h​e​y​ ​e​n​t​e​r​e​d​ ​i​n​t​o​
	​ ​ ​ ​ ​a​c​t​i​o​n​?
		 */
		'525': string
		/**
		 * D​i​d​ ​y​o​u​ ​f​e​e​l​ ​t​h​a​t​ ​y​o​u​ ​n​e​e​d​e​d​ ​t​o​ ​p​a​y​ ​s​o​m​e​ ​s​o​r​t​ ​o​f​ ​b​r​i​b​e​ ​o​r​ ​g​i​f​t​ ​t​o​ ​t​h​e​
	​ ​ ​ ​ ​e​m​p​l​o​y​e​e​ ​t​o​ ​m​a​k​e​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​t​o​ ​b​e​ ​p​r​o​c​e​s​s​e​d​ ​f​a​s​t​e​r​?
		 */
		'526': string
		/**
		 * H​a​s​ ​y​o​u​r​ ​m​a​t​t​e​r​ ​b​e​e​n​ ​d​e​a​l​t​ ​w​i​t​h​ ​b​y​ ​t​h​e​ ​S​A​S​B​ ​i​t​s​e​l​f​ ​o​r​ ​h​a​v​e​ ​y​o​u​ ​b​e​e​n​
	​ ​ ​ ​ ​r​e​f​e​r​r​e​d​ ​t​o​ ​a​n​o​t​h​e​r​ ​e​n​t​i​t​y​?
		 */
		'527': string
		/**
		 * H​a​s​ ​t​h​e​ ​p​r​o​b​l​e​m​ ​b​e​e​n​ ​r​e​s​o​l​v​e​d​?
		 */
		'528': string
		/**
		 * H​o​w​ ​l​o​n​g​ ​d​i​d​ ​t​h​e​ ​r​e​s​o​l​u​t​i​o​n​ ​t​a​k​e​ ​s​i​n​c​e​ ​y​o​u​ ​h​a​v​e​ ​p​u​t​ ​i​n​ ​t​h​e​ ​r​e​q​u​e​s​t​?
		 */
		'529': string
		/**
		 * S​i​n​c​e​ ​A​p​r​i​l​ ​2​0​2​1​,​ ​h​a​v​e​ ​y​o​u​ ​c​o​n​t​a​c​t​e​d​ ​s​o​m​e​o​n​e​ ​t​o​ ​r​e​s​o​l​v​e​ ​t​h​e​ ​D​R​A​I​N​A​G​E​
	​ ​ ​ ​ ​i​s​s​u​e​s​ ​y​o​u​ ​f​a​c​e​d​ ​b​e​f​o​r​e​?
		 */
		'612': string
		/**
		 * W​h​e​n​ ​w​a​s​ ​t​h​e​ ​l​a​s​t​ ​t​i​m​e​ ​y​o​u​ ​c​o​n​t​a​c​t​e​d​ ​s​o​m​e​o​n​e​ ​f​o​r​ ​h​e​l​p​ ​w​i​t​h​ ​a​
	​ ​ ​ ​ ​d​r​a​i​n​a​g​e​ ​p​r​o​b​l​e​m​?
		 */
		'613': string
		/**
		 * W​h​a​t​ ​w​a​s​ ​t​h​e​ ​p​r​o​b​l​e​m​ ​a​b​o​u​t​?
		 */
		'614': string
		/**
		 * S​p​e​c​i​f​y​ ​o​t​h​e​r
		 */
		'615': string
		/**
		 * W​h​o​ ​d​i​d​ ​y​o​u​ ​c​o​n​t​a​c​t​?
		 */
		'616': string
		/**
		 * W​h​y​ ​d​i​d​n​'​t​ ​y​o​u​ ​c​o​n​t​a​c​t​ ​S​A​S​B​ ​f​o​r​ ​t​h​e​ ​p​r​o​b​l​e​m​?
		 */
		'617': string
		/**
		 * (​C​a​s​o​ ​t​e​n​h​a​ ​c​o​n​t​a​c​t​a​d​o​ ​o​ ​S​A​S​B​)​,​ ​a​ ​p​e​s​s​o​a​ ​q​u​e​ ​l​h​e​ ​a​t​e​n​d​e​u​ ​t​r​a​t​o​u​-​l​h​e​ ​d​u​m​a​ ​f​o​r​m​a​ ​c​o​r​r​e​c​t​a​ ​e​ ​e​d​u​c​a​d​a​?
		 */
		'618': string
		/**
		 * (​C​a​s​o​ ​t​e​n​h​a​ ​s​i​d​o​ ​o​ ​S​A​S​B​)​,​ ​t​e​v​e​ ​q​u​e​ ​f​a​z​e​r​ ​m​a​i​s​ ​q​u​e​ ​u​m​a​ ​c​h​a​m​a​d​a​ ​a​t​é​ ​q​u​e​ ​c​o​m​e​ç​a​r​a​m​ ​a​ ​i​n​t​e​r​v​i​r​?
		 */
		'619': string
		/**
		 * (​C​a​s​o​ ​t​e​n​h​a​ ​c​o​n​t​a​c​t​a​d​o​ ​o​ ​S​A​S​B​)​,​ ​s​e​n​t​i​u​ ​a​ ​n​e​c​e​s​s​i​d​a​d​e​ ​d​e​ ​s​u​b​o​r​n​a​r​ ​o​u​ ​o​f​e​r​e​c​e​r​ ​a​l​g​o​ ​a​o​ ​f​u​n​c​i​o​n​á​r​i​o​ ​p​a​r​a​ ​q​u​e​ ​o​ ​a​t​e​n​d​i​m​e​n​t​o​ ​f​o​s​s​e​ ​r​á​p​i​d​o​?
		 */
		'620': string
		/**
		 * (​C​a​s​o​ ​t​e​n​h​a​ ​c​o​n​t​a​c​t​a​d​o​ ​o​ ​S​A​S​B​)​,​ ​o​ ​s​e​u​ ​p​r​o​b​l​e​m​a​ ​f​o​i​ ​t​r​a​t​a​d​o​ ​p​e​l​o​ ​p​r​ó​p​r​i​o​ ​S​A​S​B​ ​o​u​ ​f​o​i​ ​e​n​c​a​m​i​n​h​a​d​o​ ​p​a​r​a​ ​o​u​t​r​a​ ​e​n​t​i​d​a​d​e​?
		 */
		'621': string
		/**
		 * (​C​a​s​o​ ​t​e​n​h​a​ ​c​o​n​t​a​c​t​a​d​o​ ​o​ ​S​A​S​B​)​ ​O​ ​s​e​u​ ​p​o​b​l​e​m​a​ ​f​i​c​o​u​ ​r​e​s​o​l​v​i​d​o​?
		 */
		'622': string
		/**
		 * (​C​a​s​o​ ​t​e​n​h​a​ ​c​o​n​t​a​c​t​a​d​o​ ​o​ ​S​A​S​B​)​ ​Q​u​a​n​t​o​ ​t​e​m​p​o​ ​l​e​v​o​u​ ​a​ ​s​o​l​u​ç​ã​o​ ​d​o​ ​p​r​o​b​l​e​m​a​ ​c​o​n​t​a​n​d​o​ ​a​ ​p​a​r​t​i​r​ ​d​o​ ​m​o​m​e​n​t​o​ ​q​u​e​ ​f​e​z​ ​o​ ​p​r​i​m​e​i​r​o​ ​c​o​n​t​a​c​t​o​?
		 */
		'623': string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * P​l​e​a​s​e​ ​l​e​t​ ​u​s​ ​k​n​o​w​ ​t​h​e​ ​n​e​w​ ​p​r​i​c​e​ ​t​h​a​t​ ​y​o​u​ ​w​o​u​l​d​ ​b​e​ ​w​i​l​l​i​n​g​ ​t​o​ ​p​a​y​?
		 */
		willingPay: string
		/**
		 * Y​o​u​ ​w​i​l​l​ ​h​a​v​e​ ​1​0​0​ ​c​r​e​d​i​t​s​ ​t​o​ ​a​l​l​o​c​a​t​e​ ​y​o​u​r​ ​v​o​t​e​.​ ​T​h​e​ ​m​o​r​e​ ​y​o​u​ ​v​o​t​e​ ​f​o​r​ ​a​n​ ​o​p​t​i​o​n​,​ ​t​h​e​ ​m​o​r​e​ ​c​r​e​d​i​t​s​ ​y​o​u​ ​w​i​l​l​ ​c​o​n​s​u​m​e​.​ ​ ​P​l​e​a​s​e​ ​o​b​s​e​r​v​e​ ​t​h​e​ ​n​u​m​b​e​r​s​ ​o​f​ ​c​r​e​d​i​t​s​ ​l​e​f​t​ ​a​s​ ​y​o​u​ ​a​l​l​o​c​a​t​e​ ​y​o​u​r​ ​v​o​t​e​s​.​ ​A​t​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​i​s​ ​e​x​e​r​c​i​s​e​,​ ​y​o​u​ ​w​i​l​l​ ​b​e​ ​a​s​k​e​d​ ​t​o​ ​r​e​v​i​e​w​ ​y​o​u​r​ ​v​o​t​e​s​.
		 */
		QVSRInfo: string
		/**
		 * P​l​e​a​s​e​ ​l​o​o​k​ ​a​t​ ​t​h​e​ ​o​p​t​i​o​n​s​ ​p​r​o​v​i​d​e​d​ ​a​n​d​ ​i​n​d​i​c​a​t​e​ ​h​o​w​ ​m​a​n​y​ ​v​o​t​e​s​ ​y​o​u​
	​ ​ ​ ​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​a​l​l​o​c​a​t​e​ ​t​o​ ​e​a​c​h​ ​p​r​i​c​e​ ​o​p​t​i​o​n​.​ ​I​f​ ​y​o​u​ ​d​i​s​l​i​k​e​ ​a​n​y​ ​o​f​ ​t​h​e​
	​ ​ ​ ​ ​o​p​t​i​o​n​s​,​ ​y​o​u​ ​c​a​n​ ​a​l​s​o​ ​"​d​o​w​n​v​o​t​e​"​ ​t​h​e​m​.
		 */
		QVSRInstruction: string
		/**
		 * I​ ​d​o​n​'​t​ ​k​n​o​w
		 */
		IDK: string
		/**
		 * P​l​e​a​s​e​ ​u​s​e​ ​t​h​e​ ​s​l​i​d​e​r​ ​t​o​ ​i​n​d​i​c​a​t​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​p​r​i​c​e​.
		 */
		SliderInstruction: string
	}
}

export type TranslationFunctions = {
	errors: {
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Expected a number
		 */
		number: () => LocalizedString
		/**
		 * Expected an answer
		 */
		string: () => LocalizedString
	}
	placeholder: {
		/**
		 * Month
		 */
		month: () => LocalizedString
		/**
		 * Year
		 */
		year: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Relationship
		 */
		relationship: () => LocalizedString
		/**
		 * Closeness
		 */
		closeness: () => LocalizedString
		/**
		 * Add Person
		 */
		addPerson: () => LocalizedString
		/**
		 * Reset
		 */
		reset: () => LocalizedString
		/**
		 * Your survey has been submitted.
		 */
		completion: () => LocalizedString
		/**
		 * Agree
		 */
		agree: () => LocalizedString
		/**
		 * Disagree
		 */
		disagree: () => LocalizedString
		/**
		 * Credits
		 */
		credits: () => LocalizedString
		/**
		 * Before proceeding with the Civicbase portion of this survey, please return to ODK and make sure that you have submitted the ODK form
		 */
		ODKConfirmation: () => LocalizedString
		/**
		 * Yes, I have submitted the ODK form, I can proceed
		 */
		ODKCTA: () => LocalizedString
	}
	help: {
		/**
		 * Not at all Important
		 */
		notImportant: () => LocalizedString
		/**
		 * Very Important
		 */
		veryImportant: () => LocalizedString
		/**
		 * Strongly Disagree
		 */
		stronglyDisagree: () => LocalizedString
		/**
		 * Strongly Agree
		 */
		stronglyAgree: () => LocalizedString
	}
	choices: {
		'48': {
			/**
			 * piped water provision for households in the city
			 */
			'0': () => LocalizedString
			/**
			 * sewer connection services in the city
			 */
			'1': () => LocalizedString
			/**
			 * drainage provision in the city
			 */
			'2': () => LocalizedString
			/**
			 * electricity supply for households in your city.
			 */
			'3': () => LocalizedString
			/**
			 * coverage of paved roads in your city.
			 */
			'4': () => LocalizedString
		}
		'430': {
			/**
			 * Don't know how to contact
			 */
			'0': () => LocalizedString
			/**
			 * SASB usually take so long
			 */
			'1': () => LocalizedString
			/**
			 * SASB will not solve that problem for me
			 */
			'2': () => LocalizedString
			/**
			 * Do not trust SASB
			 */
			'3': () => LocalizedString
			/**
			 * Someone else will call
			 */
			'4': () => LocalizedString
			/**
			 * More convenient to call a plumber to fix my problem
			 */
			'5': () => LocalizedString
			/**
			 * Cheaper to call a plumber
			 */
			'6': () => LocalizedString
		}
		'431': {
			/**
			 * Fecal Sludge removal
			 */
			'0': () => LocalizedString
			/**
			 * Fecal Sludge Removal (Priority Request)
			 */
			'1': () => LocalizedString
			/**
			 * Cleaning of Septic Tank
			 */
			'2': () => LocalizedString
		}
		'510': {
			/**
			 * Not enough water to flush
			 */
			'0': () => LocalizedString
			/**
			 * Sewer blockage, no proper flow, flow of black water, over flow in your dwelling or compound
			 */
			'1': () => LocalizedString
			/**
			 * Sewer blockage, no proper flow, flow of black water, over flow in your block
			 */
			'2': () => LocalizedString
			/**
			 * Sewer line leakage/breakage in your dwelling
			 */
			'3': () => LocalizedString
			/**
			 * Sewer line leakage/breakage in your neighborhood
			 */
			'4': () => LocalizedString
			/**
			 * Bad sewer smell in your dwelling
			 */
			'5': () => LocalizedString
			/**
			 * Connection cutoff due to not paying bill
			 */
			'6': () => LocalizedString
			/**
			 * Other
			 */
			'7': () => LocalizedString
		}
		'513': {
			/**
			 * Don't know how to contact
			 */
			'0': () => LocalizedString
			/**
			 * SASB usually take so long
			 */
			'1': () => LocalizedString
			/**
			 * SASB will not solve that problem for me
			 */
			'2': () => LocalizedString
			/**
			 * Do not trust SASB
			 */
			'3': () => LocalizedString
			/**
			 * Someone else will call
			 */
			'4': () => LocalizedString
			/**
			 * More convenient to call a plumber to fix my problem
			 */
			'5': () => LocalizedString
			/**
			 * Cheaper to call a plumber
			 */
			'6': () => LocalizedString
		}
		'614': {
			/**
			 * Channels and boxes open
			 */
			'0': () => LocalizedString
			/**
			 * Overflowing boxes
			 */
			'1': () => LocalizedString
			/**
			 * Flooded roads
			 */
			'2': () => LocalizedString
			/**
			 * Flooded courtyard after rain
			 */
			'3': () => LocalizedString
			/**
			 * House flooded after rain
			 */
			'4': () => LocalizedString
			/**
			 * Other
			 */
			'5': () => LocalizedString
		}
		'617': {
			/**
			 * Don't know how to contact
			 */
			'0': () => LocalizedString
			/**
			 * SASB usually take so long
			 */
			'1': () => LocalizedString
			/**
			 * SASB will not solve that problem for me
			 */
			'2': () => LocalizedString
			/**
			 * Do not trust SASB
			 */
			'3': () => LocalizedString
			/**
			 * Someone else will call
			 */
			'4': () => LocalizedString
			/**
			 * More convenient to call a plumber to fix my problem
			 */
			'5': () => LocalizedString
			/**
			 * Cheaper to call a plumber
			 */
			'6': () => LocalizedString
		}
		/**
		 * Not Sharing with Anyone
		 */
		notSharing: () => LocalizedString
		likely: {
			/**
			 * Very Unlikely
			 */
			'0': () => LocalizedString
			/**
			 * Somewhat unlikely
			 */
			'1': () => LocalizedString
			/**
			 * Somewhat likely
			 */
			'2': () => LocalizedString
			/**
			 * Very Likely
			 */
			'3': () => LocalizedString
		}
		importance: {
			/**
			 * Not at all important
			 */
			'0': () => LocalizedString
			/**
			 * Low importance
			 */
			'1': () => LocalizedString
			/**
			 * Important
			 */
			'2': () => LocalizedString
			/**
			 * Very Important
			 */
			'3': () => LocalizedString
		}
		/**
		 * Do you agree with the allocation of your votes? If you agree, select next. If not, you may click on reset and reallocate your votes.
		 */
		QVSRReset: () => LocalizedString
		howLong: {
			/**
			 * A few days but within a week
			 */
			'0': () => LocalizedString
			/**
			 * Between 1 and 2 weeks
			 */
			'1': () => LocalizedString
			/**
			 * Less than a month
			 */
			'2': () => LocalizedString
			/**
			 * More than a month
			 */
			'3': () => LocalizedString
		}
		entity: {
			/**
			 * Referred to another entity
			 */
			'0': () => LocalizedString
			/**
			 * Dealth by SASB
			 */
			'1': () => LocalizedString
		}
		problems: {
			/**
			 * Yes, during 1 or 2 months (Rarely)
			 */
			'0': () => LocalizedString
			/**
			 * Yes, 3 months or more but not all (Sometimes)
			 */
			'1': () => LocalizedString
			/**
			 * Yes, all months (Regularly)
			 */
			'2': () => LocalizedString
			/**
			 * No, never
			 */
			'3': () => LocalizedString
		}
		relationship: {
			/**
			 * Neighbor
			 */
			'0': () => LocalizedString
			/**
			 * Work Colleague
			 */
			'1': () => LocalizedString
			/**
			 * Friend Acquaintance
			 */
			'2': () => LocalizedString
			/**
			 * Family Member
			 */
			'3': () => LocalizedString
			/**
			 * Other
			 */
			'4': () => LocalizedString
		}
		/**
		 * Not Applicable (Only emptied once since April 2021)
		 */
		notAplicable: () => LocalizedString
		/**
		 * Not Aplicable
		 */
		notAplicable2: () => LocalizedString
		satisfy: {
			/**
			 * Very Satisfied
			 */
			'0': () => LocalizedString
			/**
			 * Satisfied
			 */
			'1': () => LocalizedString
			/**
			 * Less satisfied
			 */
			'2': () => LocalizedString
			/**
			 * Dissatisfied
			 */
			'3': () => LocalizedString
		}
		satisfaction: {
			/**
			 * It has gotten worse
			 */
			'0': () => LocalizedString
			/**
			 * No change
			 */
			'1': () => LocalizedString
			/**
			 * It has improved
			 */
			'2': () => LocalizedString
			/**
			 * Don't know
			 */
			'3': () => LocalizedString
		}
		satisfactionLevel: {
			/**
			 * Satisfied
			 */
			'0': () => LocalizedString
			/**
			 * Somewhat Satisfied
			 */
			'1': () => LocalizedString
			/**
			 * Somewhat Dissatisfied
			 */
			'2': () => LocalizedString
			/**
			 * Dissastisfied
			 */
			'3': () => LocalizedString
		}
		serviceProvider: {
			/**
			 * Landlord
			 */
			'0': () => LocalizedString
			/**
			 * Intermediary
			 */
			'1': () => LocalizedString
			/**
			 * SASB
			 */
			'2': () => LocalizedString
			/**
			 * Private operator
			 */
			'3': () => LocalizedString
			/**
			 * Manager of condominium/building
			 */
			'4': () => LocalizedString
			/**
			 * Other
			 */
			'5': () => LocalizedString
		}
		months: {
			/**
			 * January
			 */
			'0': () => LocalizedString
			/**
			 * February
			 */
			'1': () => LocalizedString
			/**
			 * March
			 */
			'2': () => LocalizedString
			/**
			 * April
			 */
			'3': () => LocalizedString
			/**
			 * May
			 */
			'4': () => LocalizedString
			/**
			 * June
			 */
			'5': () => LocalizedString
			/**
			 * July
			 */
			'6': () => LocalizedString
			/**
			 * August
			 */
			'7': () => LocalizedString
			/**
			 * September
			 */
			'8': () => LocalizedString
			/**
			 * October
			 */
			'9': () => LocalizedString
			/**
			 * November
			 */
			'10': () => LocalizedString
			/**
			 * December
			 */
			'11': () => LocalizedString
		}
		revise: {
			/**
			 * Revise up
			 */
			'0': () => LocalizedString
			/**
			 * Stay the same
			 */
			'1': () => LocalizedString
			/**
			 * Revise down
			 */
			'2': () => LocalizedString
		}
		compare: {
			/**
			 * Higher
			 */
			'0': () => LocalizedString
			/**
			 * About Right
			 */
			'1': () => LocalizedString
			/**
			 * Lower
			 */
			'2': () => LocalizedString
		}
		yesNo: {
			/**
			 * Yes
			 */
			'0': () => LocalizedString
			/**
			 * No
			 */
			'1': () => LocalizedString
		}
		/**
		 * Please select one option
		 */
		placeholder: () => LocalizedString
		languages: {
			/**
			 * English
			 */
			'0': () => LocalizedString
			/**
			 * Portuguese
			 */
			'1': () => LocalizedString
		}
		sanitationType: {
			/**
			 * sewer connection
			 */
			'0': () => LocalizedString
			/**
			 * Septic Tank
			 */
			'1': () => LocalizedString
		}
		dwellingType: {
			/**
			 * Singular
			 */
			'0': () => LocalizedString
			/**
			 * Compound separated sanitation
			 */
			'1': () => LocalizedString
			/**
			 * Compound shared sanitation
			 */
			'2': () => LocalizedString
			/**
			 * Appartment in multistoried building with shared sanitation
			 */
			'3': () => LocalizedString
		}
	}
	actions: {
		/**
		 * Enable Location
		 */
		enableLocation: () => LocalizedString
		/**
		 * Start Survey
		 */
		startSurvey: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Previous
		 */
		previous: () => LocalizedString
		/**
		 * Submit
		 */
		submit: () => LocalizedString
	}
	headings: {
		/**
		 * Background Data
		 */
		'1': () => LocalizedString
		/**
		 * Background Data
		 */
		'2': () => LocalizedString
		/**
		 * Background Data
		 */
		'3': () => LocalizedString
		/**
		 * Service Prioritization
		 */
		'4': () => LocalizedString
		/**
		 * Information Experiment
		 */
		'5': () => LocalizedString
		/**
		 * Sharing Information
		 */
		'6': () => LocalizedString
		/**
		 * WTP - Sewer Connection Fee
		 */
		'7': () => LocalizedString
		/**
		 * Community Price Point - Sewer Connection Fee
		 */
		'8': () => LocalizedString
		/**
		 * WTP - Monthly Sanitation Tax/Sewer Service Fee
		 */
		'9': () => LocalizedString
		/**
		 * Community Price Point - Monthly Sanitation Tax/Sewer Service Fee
		 */
		'10': () => LocalizedString
		/**
		 * WTP - New Monthly  Drainage Service Fee
		 */
		'11': () => LocalizedString
		/**
		 * Community Price Point - New Monthly Drainage Service Fee
		 */
		'12': () => LocalizedString
		/**
		 * WTP for Fecal Sludge Management Services
		 */
		'13': () => LocalizedString
		/**
		 * WTP for Fecal Sludge Management Services
		 */
		'14': () => LocalizedString
		/**
		 * Information Experiment - Reminder
		 */
		'15': () => LocalizedString
		/**
		 * Satisfaction towards SASB's Services
		 */
		'16': () => LocalizedString
		/**
		 * Sharing of Satisfaction
		 */
		'17': () => LocalizedString
		'18': () => LocalizedString
		/**
		 * Experience with Household Sewer Services
		 */
		'19': () => LocalizedString
		/**
		 * Experience Interacting with SASB when dealing with Sewer ISSUES
		 */
		'20': () => LocalizedString
		/**
		 * Revising WTP: Sewer Connection Fee
		 */
		'21': () => LocalizedString
		/**
		 * Revising WTP : Monthly Sanitation Tax/Sewer Service Fee
		 */
		'22': () => LocalizedString
		/**
		 * Experience Interacting with SASB when dealing with Septic Tank
		 */
		'23': () => LocalizedString
		/**
		 * Revising WTP: Fecal Sludge Desludging Services
		 */
		'24': () => LocalizedString
		/**
		 * Experience with Drainage Condition
		 */
		'25': () => LocalizedString
		/**
		 * Experience Interacting with SASB when dealing with Drainage Issues
		 */
		'26': () => LocalizedString
		'27': () => LocalizedString
	}
	questions: {
		/**
		 * Please enter unique ID
		 */
		'41': () => LocalizedString
		/**
		 * Neighborhood
		 */
		'42': () => LocalizedString
		/**
		 * What type of sanitation service do you have?
		 */
		'43': () => LocalizedString
		/**
		 * What type of dweling is this?
		 */
		'44': () => LocalizedString
		/**
		 * Do you share your water bill with other households?
		 */
		'45': () => LocalizedString
		/**
		 * With how many households do you share your water bill?
		 */
		'46': () => LocalizedString
		/**
		 * Based on information we have collected, we found that households in
	    your community typically pays around 620 meticals for the monthly
	    water bill including the sanitation tax. How does this compare to the
	    amount you typically pay?
		 */
		'47': () => LocalizedString
		'48': {
			/**
			 * Residents in your neighborhood are being asked to participate in a vote. When you make your decisions, please imagine everyone else in your neighborhood will be participating in this exercise too.
			 */
			paragraph1: () => LocalizedString
			/**
			 * Please distribute your votes according to the importance the following public services have for you today
			 */
			paragraph2: () => LocalizedString
		}
		'49': {
			/**
			 * I've been thinking
		      about how the utility SASB has been managing sanitation services.
		      And though I don't know much about sanitation, in my personal
		      opinion, they've been doing a good job
			 */
			paragraph1: () => LocalizedString
			/**
			 * And in order to improve service quality, SASB has implemented an
		      innovative new training program for its workers since February 2022.
		      The program involves
			 */
			paragraph2: () => LocalizedString
			/**
			 * quickly fixing sewer blockages or bursts
			 */
			paragraph3: () => LocalizedString
			/**
			 * improving drainage
			 */
			paragraph4: () => LocalizedString
			/**
			 * promptly addressing customer complaints and
			 */
			paragraph5: () => LocalizedString
			/**
			 * reducing service disruptions.
			 */
			paragraph6: () => LocalizedString
			/**
			 * This innovative training program has improved service reliability
		      by 55 percent and complaints response time by 34 percent in
		      another country.
			 */
			paragraph7: () => LocalizedString
		}
		/**
		 * I will now ask you about your experiences with your  sewer connection in your household and neighborhood block . For each experience, we want to know in how many months this happened to you in the last 6 months. Even if it happened just once during a month, we would like to count that month
		 */
		'51': () => LocalizedString
		/**
		 * In the last 6 months, how often did you experience a sewer blockage/breakage/overflow in your neighborhood block?
		 */
		'54': () => LocalizedString
		/**
		 * If you compare the frequency of sewer blockages/breakages/overflows in your neighborhood block between April and September 2021 to those in the last 6 months, have you noticed any change?
		 */
		'55': () => LocalizedString
		/**
		 * In the last 6 months, how often did you experience bad sewer smell in your dwelling or compound?
		 */
		'56': () => LocalizedString
		/**
		 * If you compare the frequency of bad sewer smell in your dwelling or compound between April and September 2021 to those in the last 6 months, have you noticed any change?
		 */
		'57': () => LocalizedString
		/**
		 * Since April 2021, Have you ever contacted anyone to resolve your
	    sewer issues before?
		 */
		'58': () => LocalizedString
		/**
		 * When was the last time you contacted someone for help with a sewer
	    problem?
		 */
		'59': () => LocalizedString
		/**
		 * I will now ask you about your experiences with rainwater drainage around your block. For each experience, we want to know in how many months this happened to you in the last 6 months. Even if it happened just once during a month, we would like to count that month
		 */
		'61': () => LocalizedString
		/**
		 * In the last 6 months, how often did the drainage boxes in your neighborhood block got obstructed and overflowed?
		 */
		'62': () => LocalizedString
		/**
		 * In the last 6 months, how often did you see that a drainage ditch/manhole was left open in your neighborhood block?
		 */
		'64': () => LocalizedString
		/**
		 * In the last 6 months, how often  have you had to walk through water?
		 */
		'66': () => LocalizedString
		/**
		 * In the last 6 months, how often were you afraid of catching a disease because of stagnant water on the street?
		 */
		'68': () => LocalizedString
		/**
		 * If you compare the frequency of water logging and stagnant water in your neighborhood block between April and September 2021 to those in the past 6 months, have you noticed any change?
		 */
		'69': () => LocalizedString
		/**
		 * I've been thinking about
	    how the utility SASB has been managing sanitation services. And though
	    I don't know much about sanitation, in my personal opinion, they've
	    been doing a good job
		 */
		'410': () => LocalizedString
		/**
		 * One the scale of 1 to 4, with 1 being not at all important and 4 being very important, do you think what I have just shared with you is important to you and the people in this neighborhood?
		 */
		'411': () => LocalizedString
		/**
		 * On the scale of 1 to 4 with one being the lowest and  4 being the highest,how likely are you to share what I have just told you to other people in this neighborhood?
		 */
		'412': () => LocalizedString
		'413': {
			/**
			 * In this survey, everyone in this neighborhood is being asked to help decide the price for the sewer connection fee. As you cast your votes or make your decisions, please imagine that everyone else in your neighborhood is also participating in this exercise. Thus, the collective decision by the neighborhood will be important for SASB to decide the pricing of their sewer connection fee.
			 */
			paragraph1: () => LocalizedString
			/**
			 * Pediram a todos os moradores do seu bairro para ajudar na tomada de decisão sobre a taxa de ligação ao esgoto. Quando votar ou tomar as suas decisões, por favor imagine que todos os seus vizinhos também participam deste exercício também.  Assim, a decisão colectiva sobre bairro será importante para o SASB tomar uma decisão em relação ao valor da taxa da ligação ao sistema de esgoto
			 */
			paragraph2: () => LocalizedString
		}
		'414': {
			/**
			 * survey, everyone in this neighborhood is being asked to help decide the
		      price for the sewer connection fee. As you cast your votes or make your
		      decisions, please imagine that everyone else in your neighborhood is
		      also participating in this exercise. Thus, the collective decision by
		      the neighborhood will be important for SASB to decide the pricing of
		      their sewer connection fee.
			 */
			paragraph1: () => LocalizedString
			/**
			 * For households who would want a NEW sewer connection, they will be
		      required to pay a ONE TIME fee which covers the material and labor cost
		      of constructing the sewer lines. What should the sewer connection fee be
		      for everyone in your neighborhood including yourself ? You may allocate
		      your votes for more than one of the price options below.
			 */
			paragraph2: () => LocalizedString
		}
		'415': {
			/**
			 * Now we would like to share with
		      you what your community thinks about the price to be paid for the sewer
		      connection fee.
			 */
			paragraph1: () => LocalizedString
			/**
			 * For the sewer connection fee. They propose an average price of (X),
		      whereas you proposed the price ({y} MT).
			 */
			paragraph2: (arg: { y: unknown }) => LocalizedString
			/**
			 * Having heard the community's proposal , would you like to revise your
		      previously stated price? Remember, your proposed price is ({y} MT)
			 */
			paragraph3: (arg: { y: unknown }) => LocalizedString
		}
		'417': {
			/**
			 * NOW, we will be
		      asking you about your willingness to pay for the monthly sanitation tax
		      or sewer service fee.
			 */
			paragraph1: () => LocalizedString
			/**
			 * In this survey, everyone in this neighborhood is being asked to help
		      decide the price for the monthly sanitation tax or the sewer service
		      fee. Currently, this constitutes 20 percent of your water bill. Based on
		      the infromation we collected, this is roughly 80 meticals per month for
		      each household across Beira. As you cast your votes or make your
		      decisions, please imagine everyone else in your neighborhood will be
		      participating in this exercise too. Thus, the collective decision by the
		      neighborhood will be important for SASB to decide the pricing of their
		      services.
			 */
			paragraph2: () => LocalizedString
			/**
			 * The monthly sanitation tax covers the costs of maintaining and repairing
		      the sewer lines. What should the monthly tax be for everyone in your
		      neighborhood including yourself?
			 */
			paragraph3: () => LocalizedString
		}
		'418': {
			/**
			 * NOW, we
		      will be asking you about your willingness to pay for the monthly
		      sanitation tax or sewer service fee.
			 */
			paragraph1: () => LocalizedString
			/**
			 * In this survey, everyone in this neighborhood is being asked to help
		      decide the price for the monthly sanitation tax or the sewer service
		      fee. Currently, this constitutes 20 percent of your water bill. Based on
		      the infromation we collected, this is roughly 80 meticals per month for
		      each household across Beira. As you cast your votes or make your
		      decisions, please imagine everyone else in your neighborhood will be
		      participating in this exercise too. Thus, the collective decision by the
		      neighborhood will be important for SASB to decide the pricing of their
		      services.
			 */
			paragraph2: () => LocalizedString
			/**
			 * The monthly sanitation tax covers the costs of maintaining and repairing
		      the sewer lines. What should the monthly tax be for everyone in your
		      neighborhood including yourself?
			 */
			paragraph3: () => LocalizedString
		}
		'419': {
			/**
			 * Now we would like to share with
		      you what your community thinks about the price to be paid for the
		      monthly sanitation tax
			 */
			paragraph1: () => LocalizedString
			/**
			 * For the monthly sanitation tax, They propose an average price of (X).
		      You proposed the price ({y} MT).
			 */
			paragraph2: (arg: { y: unknown }) => LocalizedString
			/**
			 * Having heard the community's proposal , would you like to revise your
		      previously stated price? Remember, your proposed price is ({y} MT)
			 */
			paragraph3: (arg: { y: unknown }) => LocalizedString
		}
		/**
		 * Since April 2021, have you ever emptied your septic tank?
		 */
		'425': () => LocalizedString
		/**
		 * Did you contact a service provider to empty the cesspool?
		 */
		'426': () => LocalizedString
		/**
		 * When was the last time you contacted someone to empty the
	    cesspool?
		 */
		'427': () => LocalizedString
		/**
		 * Who did you contact?
		 */
		'428': () => LocalizedString
		/**
		 * Specify other
		 */
		'429': () => LocalizedString
		/**
		 * Why didn't you contact SASB for the problem?
		 */
		'430': () => LocalizedString
		/**
		 * What services did you request
		 */
		'431': () => LocalizedString
		/**
		 * Did you pay for the service?
		 */
		'432': () => LocalizedString
		/**
		 * How much did you pay for the service?
		 */
		'433': () => LocalizedString
		/**
		 * Currently, SASB offers the
	    service to remove the fecal sludge and clean your septic tank for a
	    total of 8700MT.
		 */
		'434': () => LocalizedString
		/**
		 * As I mentioned
	    earlier, in my personal opinion, SASB have been doing a good job! They
	    have also implemented a spacial training program to improve
	    performance of its workers. This innovative training program has
	    improved service reliability and coplaints response previously in
	    another county
		 */
		'439': () => LocalizedString
		/**
		 * As I mentioned earlier, in my personal opinion, SASB have been doing a good job!
		 */
		'440': () => LocalizedString
		/**
		 * Overall, are you satisfied with the quality of your CURRENT sewer
	    services?
		 */
		'441': () => LocalizedString
		/**
		 * If you compare the quality of sewer services you received between
	    April and September 2021 to the services you received in the last
	    6 months, have you noticed any improvements?
		 */
		'442': () => LocalizedString
		/**
		 * Overall, are you satisfied with the quality of drainage services by
	    SASB in your neighborhood?
		 */
		'443': () => LocalizedString
		/**
		 * If you compare the quality of drainage services between April and
	    September 2021 tothe services in the last 6 months, have you noticed
	    any improvements?
		 */
		'444': () => LocalizedString
		/**
		 * Overall, are you satisfied with the quality of SASB fecal sludge
	    desludging services?
		 */
		'445': () => LocalizedString
		/**
		 * If you compare the quality of fecal sludge desludging services you received between April and September 2021 to the services you received in the last 6 months, have you noticed any changes?
		 */
		'446': () => LocalizedString
		/**
		 * Overall, are you satisfied with the quality of SASB customer service
	    when responding to your questions, complaints and requests?
		 */
		'447': () => LocalizedString
		/**
		 * If you compare the quality of SASB's CUSTOMER services you received between April and September 2021 to the services you received in the last 6 months, have you noticed any change?
		 */
		'448': () => LocalizedString
		/**
		 * Overall, are you satisfied with the quality of public service by the
	    Municipality of Beira?
		 */
		'449': () => LocalizedString
		/**
		 * If you compare the quality of Beira Municipality's public services you received between April and September 2021 to the services you received in the last 6 months, have you noticed any change?
		 */
		'450': () => LocalizedString
		/**
		 * On the scale of 1 to 4, with 1 being the lowest and 4 being the highest, how likely are you to share YOUR SATISFACTION towards the SASB's services mentioned above to other people in this neighborhood?
		 */
		'451': () => LocalizedString
		/**
		 * With whom would you like to share YOUR SATISFACTION/OPINON to?  You may provide up to 3 names. Specify your relationship and closeness for each person. For closeness , please refer to the diagram provided above. If you would not like to share your SATISFACTION to anyone , select the option "No One"
		 */
		'452': () => LocalizedString
		/**
		 * As previously mentioned at the start of the survey, your responses will be confidential. However, today, you have a chance to submit your satisfaction directly to SASB through us. This will enable them to follow up with you. Would you like to do that ? (There is no obligation to submit this to SASB)
		 */
		'453': () => LocalizedString
		/**
		 * Do you know how to contact SASB when you are faced with sanitation or
	    drainage related issues?
		 */
		'454': () => LocalizedString
		/**
		 * What was the sewage related problem?
		 */
		'510': () => LocalizedString
		/**
		 * Who did you contact?
		 */
		'511': () => LocalizedString
		/**
		 * Specify other
		 */
		'512': () => LocalizedString
		/**
		 * Why didn't you contact SASB for the problem?
		 */
		'513': () => LocalizedString
		/**
		 * Did the person who dealt with your complaint treat you in a fair and
	    polite manner?
		 */
		'514': () => LocalizedString
		/**
		 * Did you need to make more than one call before they entered into
	    action?
		 */
		'515': () => LocalizedString
		/**
		 * Did you feel that you needed to pay some sort of bribe or gift to
	    the employee to make the request to be processed faster?
		 */
		'516': () => LocalizedString
		/**
		 * Has your matter been dealt with by the SASB itself or have you been
	    referred to another entity?
		 */
		'517': () => LocalizedString
		/**
		 * Has the problem been resolved?
		 */
		'518': () => LocalizedString
		/**
		 * How long did the resolution take since you have put in the request?
		 */
		'519': () => LocalizedString
		/**
		 * On reflection, would you like to revise the previously stated price
	    for the one time sewer connection fee? Remember, your proposed price
	    is ({y} MT)
		 */
		'520': (arg: { y: unknown }) => LocalizedString
		/**
		 * On reflection, would you like to revise the previously stated price
	    for the for the monthly sanitation tax or sewer service fee? Remember,
	    your proposed price is ({y} MT)
		 */
		'522': (arg: { y: unknown }) => LocalizedString
		/**
		 * Did the person who dealt with your complaint treat you in a fair and
	    polite manner?
		 */
		'524': () => LocalizedString
		/**
		 * Did you need to make more than one call before they entered into
	    action?
		 */
		'525': () => LocalizedString
		/**
		 * Did you feel that you needed to pay some sort of bribe or gift to the
	    employee to make the request to be processed faster?
		 */
		'526': () => LocalizedString
		/**
		 * Has your matter been dealt with by the SASB itself or have you been
	    referred to another entity?
		 */
		'527': () => LocalizedString
		/**
		 * Has the problem been resolved?
		 */
		'528': () => LocalizedString
		/**
		 * How long did the resolution take since you have put in the request?
		 */
		'529': () => LocalizedString
		/**
		 * Since April 2021, have you contacted someone to resolve the DRAINAGE
	    issues you faced before?
		 */
		'612': () => LocalizedString
		/**
		 * When was the last time you contacted someone for help with a
	    drainage problem?
		 */
		'613': () => LocalizedString
		/**
		 * What was the problem about?
		 */
		'614': () => LocalizedString
		/**
		 * Specify other
		 */
		'615': () => LocalizedString
		/**
		 * Who did you contact?
		 */
		'616': () => LocalizedString
		/**
		 * Why didn't you contact SASB for the problem?
		 */
		'617': () => LocalizedString
		/**
		 * (Caso tenha contactado o SASB), a pessoa que lhe atendeu tratou-lhe duma forma correcta e educada?
		 */
		'618': () => LocalizedString
		/**
		 * (Caso tenha sido o SASB), teve que fazer mais que uma chamada até que começaram a intervir?
		 */
		'619': () => LocalizedString
		/**
		 * (Caso tenha contactado o SASB), sentiu a necessidade de subornar ou oferecer algo ao funcionário para que o atendimento fosse rápido?
		 */
		'620': () => LocalizedString
		/**
		 * (Caso tenha contactado o SASB), o seu problema foi tratado pelo próprio SASB ou foi encaminhado para outra entidade?
		 */
		'621': () => LocalizedString
		/**
		 * (Caso tenha contactado o SASB) O seu poblema ficou resolvido?
		 */
		'622': () => LocalizedString
		/**
		 * (Caso tenha contactado o SASB) Quanto tempo levou a solução do problema contando a partir do momento que fez o primeiro contacto?
		 */
		'623': () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Please let us know the new price that you would be willing to pay?
		 */
		willingPay: () => LocalizedString
		/**
		 * You will have 100 credits to allocate your vote. The more you vote for an option, the more credits you will consume.  Please observe the numbers of credits left as you allocate your votes. At the end of this exercise, you will be asked to review your votes.
		 */
		QVSRInfo: () => LocalizedString
		/**
		 * Please look at the options provided and indicate how many votes you
	    would like to allocate to each price option. If you dislike any of the
	    options, you can also "downvote" them.
		 */
		QVSRInstruction: () => LocalizedString
		/**
		 * I don't know
		 */
		IDK: () => LocalizedString
		/**
		 * Please use the slider to indicate your preferred price.
		 */
		SliderInstruction: () => LocalizedString
	}
}

export type Formatters = {}
